// « Fendani — Le Secret de la Forêt sans Douleur » — Une histoire de Fatoumata Yarie Cissé.
// Collection Pati · L'Atelier Solidaire — Pati Passage (13–15 ans).
// Aborde l'excision par une approche culturelle : remplacer la lame par la parole, le chant et le savoir.
// Chants soussou + traductions conservés intacts (consigne autrice).
// FR posé en premier ; EN / AR / ZH à ajouter ensuite (même procédé que les autres livres).
export type FendaniLang = "fr" | "en" | "ar" | "zh";
type Section = { id: string; title: string; paragraphs: string[] };
type Book = { lang: FendaniLang; dir: "ltr" | "rtl"; label: string; bookTitle: string; sections: Section[] };

export const FENDANI_ML: Partial<Record<FendaniLang, Book>> = {
  fr: {
    lang: "fr", dir: "ltr", label: "Français", bookTitle: "Fendani — Le Secret de la Forêt sans Douleur",
    sections: [
      { id: "avant-propos", title: "Avant-propos", paragraphs: [
        "La culture n'est pas un monument figé dans le passé, mais un arbre vivant qui puise sa force dans ses racines pour mieux s'épanouir vers le ciel. En Guinée, nos rites d'initiation ont toujours été le ciment de notre identité, transmettant courage, pudeur et dignité aux jeunes filles.",
        "Mais le cœur de cette transmission s'est parfois perdu derrière la douleur du couteau. Fendani fait un choix : que les rites conservent toute leur puissance symbolique et éducative, en remplaçant la mutilation par la parole, le chant et la connaissance. Protéger l'intégrité physique de nos filles, et magnifier notre patrimoine.",
        "Ce conte, Le Secret de la Forêt sans Douleur, est plus qu'une histoire. C'est une promesse faite à Mayenie et à toutes les filles de notre nation : la preuve que l'on peut devenir une femme accomplie, entière et fière de ses origines, par la seule puissance de la parole et du savoir." ] },

      { id: "ch1", title: "Chapitre 1 — Le Poids du Silence", paragraphs: [
        "C'est dans une école de la capitale que commence l'histoire de Mayenie, treize ans. Ce matin-là, elle franchit le seuil de l'école primaire de Gbessia Port, son centre d'examen. La cour, bercée par la brume marine, semblait annoncer un jour qui compterait ; mais Mayenie n'y pensait pas. Son esprit était déjà tout entier tourné vers l'épreuve.",
        "Dans la salle, armée de ses stylos, elle attendait.",
        "Le surveillant : Vérifiez que vous avez vos stylos et que le numéro de PV est bien noté sur la fiche, avant le lancement de l'épreuve.",
        "L'épreuve de rédaction portait sur : « L'excision, entre tradition et santé ». Mayenie avait abordé ce sujet en sixième, puis en biologie. Elle n'avait pas trop à s'inquiéter. Pourtant, pour la première fois, elle se sentait personnellement concernée.",
        "Le soleil de Conakry tapait fort sur le toit, en ce mois de juin. Mayenie rangea ses affaires. Elle venait de passer deux heures à écrire, et les mots lui semblaient plus tranchants que d'habitude. En s'approchant du manguier où ses camarades s'abritaient, ses doigts tremblaient un peu.",
        "Aïcha : Alors, Mayenie ? Tu as écrit quoi ? Toi qui n'es pas lavée… tu ne sais même pas ce que c'est qu'être une femme vraiment.",
        "Les autres filles pouffèrent. Mayenie releva les yeux. Elle avait préparé ses mots, mais ils lui semblaient soudain trop petits.",
        "Mayenie : La maîtresse a toujours dit que c'est une question de santé. Mon corps est entier. Ça ne change pas qui je suis.",
        "Aïcha : Peut-être pour les livres. Mais pour nous, tu restes une enfant.",
        "Le groupe se dispersa en riant. Mayenie resta seule un instant, les yeux sur ses chaussures poussiéreuses. Quelque chose s'était noué dans sa poitrine. Pas de la honte, exactement. Quelque chose de lourd, comme une question sans réponse.",
        "En rentrant, l'odeur du fonio à la sauce arachide que sa maman avait cuisiné ne suffit pas à la consoler. Sur tout le chemin, les ricanements la suivaient, et la voix d'Aïcha : une enfant toute sa vie, une étrangère à ses coutumes. Elle s'assit au salon et baissa la tête. Était-il vrai que ses parents lui avaient volé son héritage en protégeant son corps ? Était-elle moins guinéenne parce qu'elle était restée entière ?",
        "Son père attendait sa championne pour entendre sa journée. Il se heurta à un mur de silence. Ce soir-là, la maison était plus calme que d'habitude. Celle qui égayait les soirées ne pipait mot. Puis, soudain :",
        "Mayenie : Maman, Papa, pourquoi vous ne m'avez pas excisée ? À l'école, on dit que je n'appartiens pas à ma culture.",
        "Un silence long et pesant. Sa mère posa son ordinateur. Son père posa son verre. Ils se regardèrent.",
        "Papa : Qui t'a dit ça ?",
        "Mayenie : Tout le monde. Pas avec des mots. Avec leurs regards. Elles disent que pour grandir, il faut passer par l'épreuve du couteau. Pourquoi vous ne me l'avez pas fait ?",
        "Le silence revint, plus lourd encore — celui de parents qui réalisaient qu'ils avaient évité cette conversation pendant des années.",
        "Le père chercha ses mots : autrefois, on croyait cette douleur nécessaire pour apprendre la patience. La mère serra contre elle sa fille qui sanglotait.",
        "Maman : Mayenie, longtemps notre société a cru que la mutilation était la porte d'entrée vers nos traditions. Beaucoup de femmes en ont souffert toute leur vie. Nous avons décidé que ton corps resterait entier, car ta valeur ne dépend pas d'une blessure. Mais tu as raison : tu mérites des mots, mon cœur, pas seulement notre silence." ] },

      { id: "ch2", title: "Chapitre 2 — Le Choix de Fendani", paragraphs: [
        "La nuit est tombée. Longtemps après que leur fille s'est endormie, les parents de Mayenie parlent à voix basse dans la cuisine. Ils ont protégé son corps. Ils ont oublié de préparer son esprit.",
        "Le silence laisse place au désaccord, puis à la recherche. La mère est catégorique : on ne touche pas au corps des filles, mais on ne perd pas ses racines. Le père s'interroge sur le poids du regard des autres, tout en refusant la barbarie de l'acte.",
        "Papa : Elle a raison. Nous lui avons évité la douleur, mais pas l'exclusion. Ce n'est pas suffisant.",
        "Maman : On a eu raison de refuser la douleur. Mais refuser ne suffit pas : nos enfants grandissent entre deux mondes, et personne ne leur propose un autre chemin.",
        "Papa : Alors c'est à nous de le proposer.",
        "La mère hoche la tête lentement. Dans ses yeux, quelque chose se décide.",
        "Maman : Nous allons créer notre propre rite. Remplacer le couteau par la parole. L'initiation par la connaissance. Et pour ça, il faut aller chercher celles qui savent… les anciennes.",
        "De l'impasse naît une résolution. Ils ne sont pas seuls dans ce cas. Ils décident d'organiser une rencontre, pour voir si d'autres parents ressentent ce même besoin : un chemin pour élever leurs filles, dans la morale et dans la santé, sans les blesser.",
        "Cette nuit-là, les parents de Mayenie ne dormirent guère. Ils écrivirent, planifièrent, téléphonèrent. À l'aube, Fendani prenait forme." ] },

      { id: "ch3", title: "Chapitre 3 — Le Retour aux Sources", paragraphs: [
        "Quelques jours plus tard, par une soirée pluvieuse, la réunion se tient dans le salon de la matriarche, Nga Nana. D'un côté, des femmes aux cheveux blancs, assises sur des nattes. De l'autre, les parents venus interroger la tradition. L'atmosphère est tendue, comme avant un orage.",
        "La maman de Mayenie : Nous ne venons pas vous juger. Vous avez été les gardiennes d'un passage, d'une transformation. Nous voulons comprendre : que transmettiez-vous vraiment, derrière l'acte ? Quels secrets portait ce rite, avant que le couteau ne prenne toute la place ?",
        "La vieille Nga Nana regarde ses mains ridées. Elle inspire, prend un long moment, comme pour se plonger dans ses souvenirs.",
        "Nga Nana : Nous enseignions la pudeur. Le respect de soi et des autres. La force qui ne se voit pas, mais qui tient debout dans les tempêtes.",
        "Elle marque une pause. Puis, plus doucement :",
        "Nga Nana : Mais c'est vrai… avec les années, le couteau est devenu plus visible que la parole. Comme si l'on avait oublié qu'il n'était que l'enveloppe, et que le cœur du rite, c'était autre chose.",
        "Mama Yéli : Fendani nous offre une chance de redevenir ce que nous étions au départ : des éducatrices. Des passeuses de sagesse. Pas des chirurgiennes de l'ombre.",
        "Les têtes blanches se tournèrent les unes vers les autres. Et pour la première fois depuis longtemps, dans cette pièce, quelque chose de doux s'installa — comme une réconciliation silencieuse avec elles-mêmes." ] },

      { id: "ch4", title: "Chapitre 4 — La Nuit du Savoir", paragraphs: [
        "Cette nuit-là, dans la cour de l'école, le ciel était dégagé. La lune brillait comme une reine entourée de ses dames de compagnie, ces étoiles qui l'acclamaient de leur scintillement. Un feu avait été allumé au centre de la cour ; les flammes dansaient dans l'air tiède. Petites et jeunes filles formaient un cercle. Les batteurs de tam-tam et le joueur de flûte, cachés derrière les feuillages, donnèrent le coup d'envoi. Les anciennes, debout, armées de wassakhoumba, commencèrent l'initiation.",
        "La cour était transformée. Les vieilles sages, les Sema, entouraient les jeunes filles. Nga Nana, vêtue d'une longue robe d'un blanc immaculé, une couronne rouge ornée d'épines et de cauris sur la tête, leva son instrument garni de bouts de calebasse et entonna le chant de la purification de l'âme.",
        "♪ Nga wobé bira khi tokhogbi nè / An nkha sa a makha khoummawali ma…",
        "« Nga Wobé est tombée dans la merde de poulets / Elle veut que je la baigne dans la rivière Khoummawali… »",
        "Les filles reprirent en chœur. Même celle que l'on traite de « crasseuse » mérite respect et soin.",
        "Nga Nana : Ne jugez jamais une personne sur ce que vous voyez du dehors. Le vrai vaut toujours plus que l'apparent.",
        "Les flammes crépitèrent plus haut. Une chouette passa dans le ciel étoilé. La voix de Nga Nana s'adoucit, et un second chant s'éleva, plus lent, plus tendre. Il était temps de célébrer l'intégrité du corps. Mama Yéli s'avança vers Mayenie et la regarda avec tendresse.",
        "♪ A tofan deh m'ma diyorè tofan deh / A tofan deh diyorè fangni tofan deh…",
        "« Elle est magnifique mon bébé / Mon doux bébé au teint d'ébène… Ses lèvres sont d'un rouge éclatant, et pourtant elle ne les trempe pas dans de l'huile rouge… »",
        "Mama Yéli : Vous êtes déjà parfaites. Vos dents, votre peau, votre sourire, votre regard. Pourquoi couper ce qui est déjà un joyau ?",
        "Mayenie comprit que son corps n'avait pas besoin d'être corrigé. Elle était déjà un joyau, une banane mûre qui portait en elle toute la splendeur de la création.",
        "Nanden Nanden enjamba quelques pas de danse sous le rythme des tam-tams, puis prit une grosse calebasse remplie d'eau et de feuilles fraîches cueillies dans la forêt sacrée, pour purifier les mains des jeunes filles, en chantant une ode à la pureté.",
        "♪ Nga Yakha keli yo, nki Sali yé donkhoe nkha nya yarakha",
        "« Mère Yakha, réveille-toi et partage un peu de ton eau de purification avec moi, que je fasse ma toilette »",
        "Mayenie sentit quelque chose se desserrer dans sa poitrine. Comme si le nœud qu'elle portait depuis la cour de récréation venait enfin de lâcher.",
        "Pour clore la session, les Sema entonnèrent le chant du marchand : la dignité de la femme est comme un pagne précieux, qu'il faut savoir porter avec honneur.",
        "♪ Nfafé Youlai Nfafé Youlai Ayi ya ! / Nfafé Youlai dougui di ndé bé ayi ya !",
        "« Oyé cher marchand, il y a un pagne ici tout frais, tout brillant… Il faut bien se tenir et faire bonne figure pour être digne. »",
        "Cette nuit-là, les filles n'apprirent pas seulement des chants. Elles apprirent à se connaître : leurs droits, leur corps, leur histoire. Elles parlèrent de santé, de respect, de l'amour que l'on se doit à soi-même. Les anciennes parlèrent longtemps, et les filles écoutèrent comme on boit de l'eau fraîche après une longue marche." ] },

      { id: "ch5", title: "Chapitre 5 — Les Ambassadrices de Fendani", paragraphs: [
        "L'aube se leva, rose et or. Le feu s'était éteint doucement. Les filles, assises en cercle, avaient les yeux brillants de fatigue et de quelque chose qui ressemblait à de la fierté. Une à une, elles reçurent leur insigne d'Ambassadrice Fendani.",
        "Hawa : Mayenie, tu es désormais une initiée du savoir. Non par la douleur, mais par la compréhension. Ton combat commence ici, ce matin, dans cette cour. Et il ira loin.",
        "Mayenie tint dans ses deux mains son bout de pagne, son collier de bambou et sa canne d'initiée. Elle pensa à Aïcha. Elle pensa à sa mère, debout dans la cuisine cette nuit-là. Elle pensa aux vieilles femmes qui avaient choisi, après toutes ces années, d'écouter et de transmettre.",
        "Mayenie : Merci, Hawa. Je n'ai plus honte. Je suis une femme africaine, guinéenne, éduquée, entière et libre.",
        "Au fond d'elle, Mayenie n'était plus la petite fille confuse de la cour de récréation. Elle était une initiée. Le secret de la forêt ne résidait pas dans la lame, mais dans ces mélodies qui lui avaient appris qui elle était.",
        "Ses parents, eux, étaient fiers d'avoir permis à leur fille de connaître la forêt. Pas n'importe laquelle : une forêt où les arbres murmurent des secrets plutôt que des cris.",
        "Les autres filles reprirent en chœur, doucement, puis de plus en plus fort, jusqu'à ce que les mots montent dans le ciel du matin comme des oiseaux. Et dans la forêt qui bordait l'école — celle que les anciens appelaient autrefois Laaga, la forêt des rites — il n'y eut plus, ce matin-là, ni cris ni larmes. Seulement des voix qui chantaient." ] },

      { id: "epilogue", title: "Épilogue — La Forêt qui Fleurit", paragraphs: [
        "Depuis cette nuit-là, d'autres cours d'école s'allument, d'autres feux, d'autres chants. De préfecture en préfecture, des filles grandissent avec la connaissance comme bouclier et la dignité comme couronne.",
        "Parce que la culture est un arbre. Elle a besoin de racines profondes et de branches qui s'ouvrent vers le ciel. Elle peut se transformer sans mourir. Elle peut transmettre sans blesser.",
        "« Fendani : parce que la culture est une richesse qui se transmet par la parole, pas par le sang. »",
        "Mayenie a treize ans, et une question qui ne la lâche pas : peut-on appartenir aux siens sans passer par le couteau ?",
        "Une nuit, dans la cour de son école, les anciennes allument un feu. Elles ne tiennent pas de lame, ce soir — seulement des chants, de l'eau de purification et la mémoire d'un rite plus vieux que la douleur. Le secret de la forêt, Mayenie va l'apprendre autrement.",
        "Une histoire de Fatoumata Yarie Cissé — Collection Pati · L'Atelier Solidaire." ] },
    ],
  },

  en: {
    lang: "en", dir: "ltr", label: "English", bookTitle: "Fendani — The Secret of the Forest Without Pain",
    sections: [
      { id: "avant-propos", title: "Foreword", paragraphs: [
        "Culture is not a monument frozen in the past, but a living tree that draws its strength from its roots in order to flourish toward the sky. In Guinea, our rites of initiation have always been the cement of our identity, passing on courage, modesty and dignity to young girls.",
        "But the heart of this transmission was sometimes lost behind the pain of the blade. Fendani makes a choice: that the rites keep all their symbolic and educational power, by replacing mutilation with speech, song and knowledge. To protect the physical integrity of our girls, and to honour our heritage.",
        "This tale, The Secret of the Forest Without Pain, is more than a story. It is a promise made to Mayenie and to all the girls of our nation: proof that one can become an accomplished woman, whole and proud of her origins, through the sole power of speech and knowledge." ] },
      { id: "ch1", title: "Chapter 1 — The Weight of Silence", paragraphs: [
        "It is in a school in the capital that the story of Mayenie, thirteen, begins. That morning, she crossed the threshold of the Gbessia Port primary school, her examination centre. The courtyard, cradled by the sea mist, seemed to announce a day that would matter; but Mayenie was not thinking of that. Her mind was already wholly turned toward the exam.",
        "In the room, armed with her pens, she waited.",
        "The invigilator: Check that you have your pens and that the report number is written on your sheet, before the test begins.",
        "The essay topic was: “Excision, between tradition and health.” Mayenie had studied this subject in sixth grade, then in biology. She had little to worry about. And yet, for the first time, she felt personally concerned.",
        "The Conakry sun beat down hard on the roof that June. Mayenie packed up her things. She had just spent two hours writing, and the words felt sharper than usual. As she approached the mango tree where her classmates were sheltering, her fingers trembled a little.",
        "Aïcha: So, Mayenie? What did you write? You who are not “washed”… you don't even know what it really means to be a woman.",
        "The other girls sniggered. Mayenie looked up. She had prepared her words, but suddenly they seemed too small.",
        "Mayenie: The teacher has always said it's a matter of health. My body is whole. That doesn't change who I am.",
        "Aïcha: Maybe in books. But to us, you're still a child.",
        "The group scattered, laughing. Mayenie stayed alone a moment, eyes on her dusty shoes. Something had tightened in her chest. Not shame, exactly. Something heavy, like a question with no answer.",
        "On the way home, the smell of the fonio with groundnut sauce her mother had cooked was not enough to console her. All along the road, the sniggers followed her, and Aïcha's voice: a child all her life, a stranger to her own customs. She sat down in the living room and lowered her head. Was it true that her parents had stolen her heritage by protecting her body? Was she less Guinean because she had remained whole?",
        "Her father was waiting for his champion to hear about her day. He met a wall of silence. That evening, the house was quieter than usual. The one who brightened the evenings did not say a word. Then, suddenly:",
        "Mayenie: Mum, Dad, why didn't you have me excised? At school they say I don't belong to my culture.",
        "A long, heavy silence. Her mother set down her computer. Her father set down his glass. They looked at each other.",
        "Dad: Who told you that?",
        "Mayenie: Everyone. Not with words. With their looks. They say that to grow up, you must go through the ordeal of the blade. Why didn't you do it to me?",
        "The silence returned, heavier still — that of parents realizing they had avoided this conversation for years.",
        "The father searched for his words: long ago, people believed this pain was necessary to learn patience. The mother held her sobbing daughter close.",
        "Mum: Mayenie, for a long time our society believed that mutilation was the gateway to our traditions. Many women suffered from it all their lives. We decided that your body would remain whole, because your worth does not depend on a wound. But you are right: you deserve words, my heart, not only our silence." ] },
      { id: "ch2", title: "Chapter 2 — Fendani's Choice", paragraphs: [
        "Night has fallen. Long after their daughter has fallen asleep, Mayenie's parents talk in low voices in the kitchen. They protected her body. They forgot to prepare her mind.",
        "Silence gives way to disagreement, then to searching. The mother is categorical: you do not touch girls' bodies, but you do not lose your roots. The father wonders about the weight of others' eyes, while refusing the barbarity of the act.",
        "Dad: She's right. We spared her the pain, but not the exclusion. It's not enough.",
        "Mum: We were right to refuse the pain. But refusing is not enough: our children grow up between two worlds, and no one offers them another path.",
        "Dad: Then it's up to us to offer it.",
        "The mother nods slowly. In her eyes, something is decided.",
        "Mum: We will create our own rite. Replace the blade with speech. Initiation with knowledge. And for that, we must go and find those who know… the elder women.",
        "From the impasse a resolution is born. They are not alone in this. They decide to organize a gathering, to see whether other parents feel the same need: a path to raise their daughters, in morality and in health, without hurting them.",
        "That night, Mayenie's parents hardly slept. They wrote, planned, made calls. By dawn, Fendani was taking shape." ] },
      { id: "ch3", title: "Chapter 3 — Return to the Source", paragraphs: [
        "A few days later, on a rainy evening, the meeting is held in the living room of the matriarch, Nga Nana. On one side, white-haired women seated on mats. On the other, the parents who have come to question tradition. The atmosphere is tense, like before a storm.",
        "Mayenie's mother: We do not come to judge you. You were the keepers of a passage, of a transformation. We want to understand: what did you really pass on, behind the act? What secrets did this rite carry, before the blade took up all the room?",
        "Old Nga Nana looks at her wrinkled hands. She breathes in, takes a long moment, as if to plunge into her memories.",
        "Nga Nana: We taught modesty. Respect for oneself and for others. The strength that cannot be seen, but that stands upright in storms.",
        "She pauses. Then, more softly:",
        "Nga Nana: But it's true… over the years, the blade became more visible than the word. As if we had forgotten that it was only the shell, and that the heart of the rite was something else.",
        "Mama Yéli: Fendani offers us a chance to become again what we were at the start: educators. Bearers of wisdom. Not surgeons of the shadows.",
        "The white heads turned toward one another. And for the first time in a long while, in that room, something gentle settled in — like a silent reconciliation with themselves." ] },
      { id: "ch4", title: "Chapter 4 — The Night of Knowledge", paragraphs: [
        "That night, in the school courtyard, the sky was clear. The moon shone like a queen surrounded by her ladies-in-waiting, those stars that cheered her with their sparkle. A fire had been lit in the centre of the courtyard; the flames danced in the warm air. Little girls and young girls formed a circle. The drummers and the flute player, hidden behind the foliage, gave the signal. The elder women, standing, armed with wassakhoumba, began the initiation.",
        "The courtyard was transformed. The wise old women, the Sema, surrounded the young girls. Nga Nana, dressed in a long, immaculate white robe, a red crown adorned with thorns and cowries on her head, raised her instrument fitted with bits of calabash and began the song of the purification of the soul.",
        "♪ Nga wobé bira khi tokhogbi nè / An nkha sa a makha khoummawali ma…",
        "“Nga Wobé has fallen into the chicken filth / She wants me to bathe her in the Khoummawali river…”",
        "The girls took up the chorus. Even the one called “filthy” deserves respect and care.",
        "Nga Nana: Never judge a person by what you see on the outside. The true is always worth more than the apparent.",
        "The flames crackled higher. An owl passed across the starry sky. Nga Nana's voice softened, and a second song rose, slower, more tender. It was time to celebrate the integrity of the body. Mama Yéli stepped toward Mayenie and looked at her tenderly.",
        "♪ A tofan deh m'ma diyorè tofan deh / A tofan deh diyorè fangni tofan deh…",
        "“She is magnificent, my baby / My sweet baby with ebony skin… Her lips are a bright red, and yet she does not dip them in red oil…”",
        "Mama Yéli: You are already perfect. Your teeth, your skin, your smile, your eyes. Why cut what is already a jewel?",
        "Mayenie understood that her body did not need to be corrected. She was already a jewel, a ripe banana carrying within her all the splendour of creation.",
        "Nanden Nanden took a few dance steps to the rhythm of the drums, then took a large calabash filled with water and fresh leaves gathered in the sacred forest, to purify the girls' hands, singing an ode to purity.",
        "♪ Nga Yakha keli yo, nki Sali yé donkhoe nkha nya yarakha",
        "“Mother Yakha, wake up and share a little of your purifying water with me, that I may wash myself.”",
        "Mayenie felt something loosen in her chest. As if the knot she had carried since the schoolyard had finally let go.",
        "To close the session, the Sema struck up the merchant's song: a woman's dignity is like a precious wrapper, which must be worn with honour.",
        "♪ Nfafé Youlai Nfafé Youlai Ayi ya ! / Nfafé Youlai dougui di ndé bé ayi ya !",
        "“O dear merchant, here is a wrapper, fresh and gleaming… One must carry oneself well to be worthy.”",
        "That night, the girls did not only learn songs. They learned to know themselves: their rights, their bodies, their history. They spoke of health, of respect, of the love one owes oneself. The elder women spoke for a long time, and the girls listened the way one drinks cool water after a long walk." ] },
      { id: "ch5", title: "Chapter 5 — The Ambassadors of Fendani", paragraphs: [
        "Dawn rose, pink and gold. The fire had died down gently. The girls, seated in a circle, had eyes bright with tiredness and with something that looked like pride. One by one, they received their Fendani Ambassador badge.",
        "Hawa: Mayenie, you are now an initiate of knowledge. Not through pain, but through understanding. Your fight begins here, this morning, in this courtyard. And it will go far.",
        "Mayenie held in both hands her piece of wrapper, her bamboo necklace and her initiate's staff. She thought of Aïcha. She thought of her mother, standing in the kitchen that night. She thought of the old women who had chosen, after all these years, to listen and to pass on.",
        "Mayenie: Thank you, Hawa. I am no longer ashamed. I am an African woman, Guinean, educated, whole and free.",
        "Deep down, Mayenie was no longer the confused little girl of the schoolyard. She was an initiate. The secret of the forest lay not in the blade, but in those melodies that had taught her who she was.",
        "Her parents, for their part, were proud to have let their daughter know the forest. Not just any forest: a forest where the trees whisper secrets instead of cries.",
        "The other girls took up the chorus, softly, then louder and louder, until the words rose into the morning sky like birds. And in the forest that bordered the school — the one the elders once called Laaga, the forest of rites — there were, that morning, no more cries or tears. Only voices that sang." ] },
      { id: "epilogue", title: "Epilogue — The Forest That Blooms", paragraphs: [
        "Since that night, other school courtyards light up, other fires, other songs. From prefecture to prefecture, girls grow up with knowledge as a shield and dignity as a crown.",
        "Because culture is a tree. It needs deep roots and branches that open toward the sky. It can transform without dying. It can pass on without wounding.",
        "“Fendani: because culture is a wealth passed on through the word, not through blood.”",
        "Mayenie is thirteen, with a question that will not let her go: can one belong to one's people without going through the blade?",
        "One night, in her school's courtyard, the elder women light a fire. They hold no blade tonight — only songs, purifying water and the memory of a rite older than pain. The secret of the forest, Mayenie will learn it another way.",
        "A story by Fatoumata Yarie Cissé — Collection Pati · L'Atelier Solidaire." ] },
    ],
  },

  ar: {
    lang: "ar", dir: "rtl", label: "العربية", bookTitle: "فينداني — سرّ الغابة بلا ألم",
    sections: [
      { id: "avant-propos", title: "تمهيد", paragraphs: [
        "الثقافة ليست نصبًا متجمّدًا في الماضي، بل شجرة حيّة تستمدّ قوّتها من جذورها لتزدهر نحو السماء. في غينيا، كانت طقوس التنشئة دائمًا أساس هويّتنا، تنقل الشجاعة والحياء والكرامة إلى الفتيات.",
        "لكنّ جوهر هذا النقل ضاع أحيانًا خلف ألم النصل. تختار فينداني أن تحتفظ الطقوس بكلّ قوّتها الرمزية والتربوية، باستبدال البتر بالكلمة والغناء والمعرفة. أن نحمي السلامة الجسدية لبناتنا، وأن نُعلي تراثنا.",
        "هذه الحكاية، سرّ الغابة بلا ألم، أكثر من مجرّد قصّة. إنها وعدٌ لِمايني ولكلّ فتيات أمّتنا: دليلٌ على أنّ المرء يمكن أن يصبح امرأة كاملة، سليمة وفخورة بأصولها، بقوّة الكلمة والمعرفة وحدها." ] },
      { id: "ch1", title: "الفصل الأول — ثِقل الصمت", paragraphs: [
        "في مدرسة بالعاصمة تبدأ قصّة مايني، ذات الثلاثة عشر عامًا. في ذلك الصباح، عبرت عتبة مدرسة غبيسيا بور الابتدائية، مركز امتحانها. بدا الفناء، الذي يداعبه ضباب البحر، وكأنه يُنبئ بيومٍ مهمّ؛ لكنّ مايني لم تفكّر في ذلك. كان عقلها كلّه منصرفًا إلى الامتحان.",
        "في القاعة، وقد تسلّحت بأقلامها، انتظرت.",
        "المراقب: تأكّدوا من أنّ معكم أقلامكم وأنّ رقم المحضر مدوَّن على البطاقة قبل بدء الاختبار.",
        "كان موضوع الإنشاء: «الختان، بين التقليد والصحّة». كانت مايني قد تناولت هذا الموضوع في الصف السادس، ثم في الأحياء. لم يكن لديها ما يقلقها كثيرًا. ومع ذلك، لأول مرّة، شعرت أنّها معنيّة شخصيًّا.",
        "كانت شمس كوناكري تضرب السقف بقوّة في شهر يونيو ذاك. رتّبت مايني أغراضها. كانت قد أمضت ساعتين في الكتابة، وبدت لها الكلمات أكثر حدّة من المعتاد. وفيما اقتربت من شجرة المانغو حيث يحتمي رفاقها، ارتجفت أصابعها قليلًا.",
        "عائشة: إذن يا مايني؟ ماذا كتبتِ؟ أنتِ التي لم تُطهَّري… لا تعرفين حتى ما معنى أن تكوني امرأة حقًّا.",
        "ضحكت الفتيات الأخريات بسخرية. رفعت مايني عينيها. كانت قد أعدّت كلماتها، لكنّها بدت لها فجأة صغيرة جدًّا.",
        "مايني: قالت المعلّمة دائمًا إنها مسألة صحّة. جسدي سليم. هذا لا يغيّر مَن أكون.",
        "عائشة: ربّما في الكتب. أمّا عندنا، فتبقين طفلة.",
        "تفرّقت المجموعة ضاحكة. بقيت مايني وحدها لحظة، وعيناها على حذائها المغبرّ. شيءٌ ما تعقّد في صدرها. ليس خجلًا بالضبط. شيءٌ ثقيل، كسؤالٍ بلا جواب.",
        "في طريق العودة، لم تكفِ رائحة الفونيو بصلصة الفول السوداني التي طبختها أمّها لتواسيها. طوال الطريق، تبعتها القهقهات وصوت عائشة: طفلة طوال حياتها، غريبة عن عاداتها. جلست في الصالة وأطرقت برأسها. أصحيحٌ أنّ والديها سرقا منها إرثها بحمايتهما جسدها؟ أهي أقلّ غينيّةً لأنها بقيت سليمة؟",
        "كان أبوها ينتظر بطلته ليسمع أخبار يومها. فاصطدم بجدارٍ من الصمت. في تلك الليلة كان البيت أهدأ من المعتاد. لم تنبس مَن كانت تُبهج السهرات بكلمة. ثم فجأة:",
        "مايني: ماما، بابا، لماذا لم تُجرِيا لي الختان؟ في المدرسة يقولون إنّي لا أنتمي إلى ثقافتي.",
        "صمتٌ طويل وثقيل. وضعت الأمّ حاسوبها. ووضع الأب كأسه. تبادلا النظرات.",
        "بابا: مَن قال لكِ هذا؟",
        "مايني: الجميع. لا بالكلمات، بل بنظراتهم. يقلن إنّه كي تكبري عليكِ أن تمرّي بمحنة النصل. لماذا لم تفعلا ذلك بي؟",
        "عاد الصمت أثقل بعد — صمت والدَين يدركان أنّهما تجنّبا هذا الحديث لسنوات.",
        "بحث الأب عن كلماته: قديمًا، كان الناس يظنّون هذا الألم ضروريًّا لتعلّم الصبر. ضمّت الأمّ ابنتها الباكية إليها.",
        "ماما: مايني، طويلًا اعتقد مجتمعنا أنّ البتر هو باب الدخول إلى تقاليدنا. عانت نساء كثيرات منه طوال حياتهنّ. قرّرنا أن يبقى جسدكِ سليمًا، لأنّ قيمتكِ لا تتوقّف على جرح. لكنّكِ محقّة: تستحقّين كلماتٍ يا قلبي، لا صمتنا وحده." ] },
      { id: "ch2", title: "الفصل الثاني — اختيار فينداني", paragraphs: [
        "حلّ الليل. بعد وقتٍ طويل من نوم ابنتهما، يتحدّث والدا مايني بصوتٍ خافت في المطبخ. حَمَيا جسدها. ونسيا أن يُعِدّا عقلها.",
        "يفسح الصمت المجال للخلاف، ثم للبحث. الأمّ حاسمة: لا نمسّ أجساد الفتيات، لكن لا نفقد جذورنا. والأب يتساءل عن وطأة نظرات الآخرين، رافضًا في الوقت نفسه وحشية الفعل.",
        "بابا: إنها محقّة. جنّبناها الألم، لكن لا الإقصاء. هذا لا يكفي.",
        "ماما: أحسنّا برفض الألم. لكنّ الرفض لا يكفي: أطفالنا يكبرون بين عالَمين، ولا أحد يقدّم لهم طريقًا آخر.",
        "بابا: إذن علينا نحن أن نقدّمه.",
        "تومئ الأمّ برأسها ببطء. في عينيها، يتقرّر شيءٌ ما.",
        "ماما: سنبتكر طقسنا الخاصّ. نستبدل النصل بالكلمة. والتنشئة بالمعرفة. ولأجل ذلك، علينا أن نبحث عمّن يعرفن… المُسنّات.",
        "من المأزق تولد عزيمة. ليسا وحدهما في هذا. يقرّران تنظيم لقاء، ليريا إن كان آباء آخرون يشعرون بالحاجة نفسها: طريقٌ لتربية بناتهم، في الأخلاق والصحّة، دون إيذائهنّ.",
        "في تلك الليلة، لم ينَم والدا مايني إلّا قليلًا. كتبا وخطّطا واتّصلا. ومع الفجر، كانت فينداني تتشكّل." ] },
      { id: "ch3", title: "الفصل الثالث — العودة إلى الأصول", paragraphs: [
        "بعد أيّامٍ قليلة، في أمسيةٍ ماطرة، يُعقد اللقاء في صالة الجدّة الكبرى، نغا نانا. في جهة، نساء بِيض الشعر جالسات على الحُصُر. وفي الأخرى، الآباء الذين جاؤوا يسائلون التقليد. الأجواء متوتّرة، كما قبل عاصفة.",
        "أمّ مايني: لم نأتِ لنحكم عليكنّ. كنتنّ حارسات عبور، حارسات تحوّل. نريد أن نفهم: ماذا كنتنّ تنقلن حقًّا، خلف الفعل؟ أيّ أسرارٍ حملها هذا الطقس قبل أن يحتلّ النصل كلّ المكان؟",
        "تنظر نغا نانا العجوز إلى يديها المجعّدتين. تتنفّس، تأخذ وقتًا طويلًا، كأنّها تغوص في ذكرياتها.",
        "نغا نانا: كنّا نعلّم الحياء. احترام الذات والآخرين. القوّة التي لا تُرى، لكنّها تصمد في العواصف.",
        "تتوقّف لحظة. ثم، بنبرةٍ أرقّ:",
        "نغا نانا: لكن صحيحٌ… مع السنين، صار النصل أوضح من الكلمة. كأنّنا نسينا أنّه لم يكن سوى القشرة، وأنّ قلب الطقس كان شيئًا آخر.",
        "ماما ييلي: تمنحنا فينداني فرصة لنعود إلى ما كنّاه في البدء: مربّيات. ناقلات حكمة. لا جرّاحاتٍ في الظلّ.",
        "التفتت الرؤوس البيضاء بعضها نحو بعض. ولأوّل مرّة منذ زمنٍ طويل، حلّ في تلك الغرفة شيءٌ لطيف — كمصالحةٍ صامتة مع الذات." ] },
      { id: "ch4", title: "الفصل الرابع — ليلة المعرفة", paragraphs: [
        "في تلك الليلة، في فناء المدرسة، كانت السماء صافية. أشرق القمر كملِكةٍ تحيط بها وصيفاتها، تلك النجوم التي تهتف له ببريقها. أُوقدت نارٌ في وسط الفناء؛ ترقص الألسنة في الهواء الدافئ. شكّلت الصغيرات والفتيات حلقة. وأعطى قارعو الطبول وعازف الناي، المختبئون خلف الأغصان، إشارة البدء. وبدأت المُسنّات، واقفات، حاملات الوَسّاخومبا، التنشئة.",
        "تحوّل الفناء. أحاطت الحكيمات العجائز، الـسيما، بالفتيات. رفعت نغا نانا، في ثوبٍ أبيض ناصع طويل، وعلى رأسها تاجٌ أحمر مزيّن بالأشواك والوَدَع، آلتها المرصّعة بقطع القرع، وأنشدت أنشودة تطهير الروح.",
        "♪ Nga wobé bira khi tokhogbi nè / An nkha sa a makha khoummawali ma…",
        "«وقعت نغا وُبي في فضلات الدجاج / تريد أن أُحمّمها في نهر خُمّاوالي…»",
        "ردّدت الفتيات الجوقة. حتى مَن تُنعَت بـ«القذرة» تستحقّ الاحترام والعناية.",
        "نغا نانا: لا تحكمن على إنسانٍ أبدًا بما ترَينه من الخارج. الحقيقيّ يساوي دائمًا أكثر من الظاهر.",
        "تعالى طقطقة اللهب. عبرت بومةٌ في السماء المرصّعة بالنجوم. لان صوت نغا نانا، وارتفعت أنشودة ثانية، أبطأ وأحنّ. حان وقت الاحتفاء بسلامة الجسد. تقدّمت ماما ييلي نحو مايني ونظرت إليها بحنان.",
        "♪ A tofan deh m'ma diyorè tofan deh / A tofan deh diyorè fangni tofan deh…",
        "«ما أجملَ طفلتي / طفلتي الحلوة ذات البشرة الأبنوسية… شفتاها حمراوان زاهيتان، ومع ذلك لا تغمسهما في زيتٍ أحمر…»",
        "ماما ييلي: أنتنّ كاملات سلفًا. أسنانكنّ، بشرتكنّ، ابتسامتكنّ، نظراتكنّ. لماذا نقطع ما هو جوهرة بالفعل؟",
        "أدركت مايني أنّ جسدها لا يحتاج إلى تصحيح. كانت جوهرة سلفًا، موزة ناضجة تحمل في داخلها كلّ بهاء الخلق.",
        "خطت نانْدِن نانْدِن بضع خطواتٍ راقصة على إيقاع الطبول، ثم أخذت قرعةً كبيرة مملوءة بالماء وبأوراقٍ طازجة جُمعت من الغابة المقدّسة، لتطهّر أيدي الفتيات، منشدةً أنشودة للطهارة.",
        "♪ Nga Yakha keli yo, nki Sali yé donkhoe nkha nya yarakha",
        "«يا أمّ ياخا، استيقظي وشاركيني قليلًا من ماء تطهيركِ، كي أغسل وجهي.»",
        "شعرت مايني بشيءٍ ينحلّ في صدرها. كأنّ العقدة التي حملتها منذ فناء المدرسة قد أفلتت أخيرًا.",
        "ولختام الجلسة، أنشدت الـسيما أنشودة التاجر: كرامة المرأة كثوبٍ ثمين، يجب أن يُحمَل بشرف.",
        "♪ Nfafé Youlai Nfafé Youlai Ayi ya ! / Nfafé Youlai dougui di ndé bé ayi ya !",
        "«يا أيّها التاجر العزيز، ها هنا ثوبٌ جديد لامع… على المرء أن يُحسن هيئته ليكون جديرًا.»",
        "في تلك الليلة، لم تتعلّم الفتيات أناشيد فحسب. تعلّمن أن يعرفن أنفسهنّ: حقوقهنّ، أجسادهنّ، تاريخهنّ. تحدّثن عن الصحّة، عن الاحترام، عن الحبّ الذي يدين به المرء لنفسه. تحدّثت المُسنّات طويلًا، وأصغت الفتيات كما يُشرَب الماء البارد بعد مسيرٍ طويل." ] },
      { id: "ch5", title: "الفصل الخامس — سفيرات فينداني", paragraphs: [
        "أطلّ الفجر ورديًّا وذهبيًّا. خمدت النار بهدوء. كانت عيون الفتيات الجالسات في حلقةٍ تلمع تعبًا وشيئًا يشبه الفخر. واحدةً تلو الأخرى، تسلّمن شارة سفيرة فينداني.",
        "هاوا: مايني، أنتِ الآن مُنتسِبة إلى المعرفة. لا بالألم، بل بالفهم. معركتكِ تبدأ هنا، هذا الصباح، في هذا الفناء. وستمضي بعيدًا.",
        "أمسكت مايني بكلتا يديها قطعة ثوبها، وعقد الخيزران، وعصا التنشئة. فكّرت في عائشة. فكّرت في أمّها، واقفةً في المطبخ تلك الليلة. فكّرت في العجائز اللواتي اخترن، بعد كلّ تلك السنين، أن يُصغين وأن يَنقُلن.",
        "مايني: شكرًا يا هاوا. لم أعد أخجل. أنا امرأة أفريقية، غينيّة، متعلّمة، سليمة وحرّة.",
        "في أعماقها، لم تعد مايني الطفلة الحائرة في فناء المدرسة. صارت مُنتسِبة. لم يكن سرّ الغابة في النصل، بل في تلك الألحان التي علّمتها مَن تكون.",
        "أمّا والداها، فكانا فخورَين بأنّهما أتاحا لابنتهما أن تعرف الغابة. لا أيّ غابة: غابة تهمس أشجارها بالأسرار بدل الصرخات.",
        "ردّدت الفتيات الأخريات الجوقة، بهدوء، ثم بصوتٍ أعلى فأعلى، حتى صعدت الكلمات في سماء الصباح كالعصافير. وفي الغابة المحاذية للمدرسة — تلك التي كان القدماء يسمّونها لاغا، غابة الطقوس — لم يعد ثمّة، ذلك الصباح، صرخاتٌ ولا دموع. أصواتٌ تغنّي فحسب." ] },
      { id: "epilogue", title: "الخاتمة — الغابة التي تُزهر", paragraphs: [
        "منذ تلك الليلة، تُضاء أفنية مدارس أخرى، ونيران أخرى، وأناشيد أخرى. من محافظةٍ إلى محافظة، تكبر فتياتٌ والمعرفة درعهنّ والكرامة تاجهنّ.",
        "لأنّ الثقافة شجرة. تحتاج إلى جذورٍ عميقة وأغصانٍ تنفتح نحو السماء. يمكنها أن تتحوّل دون أن تموت. ويمكنها أن تنقل دون أن تجرح.",
        "«فينداني: لأنّ الثقافة ثروة تُنقَل بالكلمة، لا بالدم.»",
        "مايني في الثالثة عشرة، ويلازمها سؤالٌ لا يتركها: هل يمكن أن ينتمي المرء إلى أهله دون المرور بالنصل؟",
        "ذات ليلة، في فناء مدرستها، تُوقد المُسنّات نارًا. لا يحملن نصلًا هذه الليلة — أناشيد فقط، وماء تطهير، وذاكرة طقسٍ أقدم من الألم. سرّ الغابة، ستتعلّمه مايني بطريقةٍ أخرى.",
        "قصّة بقلم فاتوماتا ياري سيسي — مجموعة باتي · لاتولييه سوليدير." ] },
    ],
  },

  zh: {
    lang: "zh", dir: "ltr", label: "中文", bookTitle: "芬达尼 — 无痛之林的秘密",
    sections: [
      { id: "avant-propos", title: "前言", paragraphs: [
        "文化不是凝固于过去的纪念碑，而是一棵从根脉汲取力量、向天空舒展的活树。在几内亚，我们的成年礼始终是身份的基石，向少女传递勇气、端庄与尊严。",
        "但这种传承的核心，有时被刀的痛苦所掩盖。芬达尼作出选择：让仪式保留其全部的象征与教育力量，以言语、歌声与知识取代切割。守护我们女儿们身体的完整，并彰显我们的传统。",
        "这则故事《无痛之林的秘密》不只是一个故事。它是对马耶妮以及全国所有女孩的承诺：证明仅凭言语与知识的力量，人也能成为一个完整、为自己出身而自豪的成熟女性。" ] },
      { id: "ch1", title: "第一章 — 沉默之重", paragraphs: [
        "马耶妮的故事，始于首都的一所学校，她十三岁。那天早晨，她踏进自己的考点——格贝西亚港小学。被海雾轻抚的院子，仿佛预示着重要的一天；但马耶妮没有想这些。她的心思早已全在考试上。",
        "在考场里，她握着笔，等待着。",
        "监考员：开考前，请检查你们带了笔，并把准考证号写在卡片上。",
        "作文题是：《割礼，在传统与健康之间》。马耶妮在六年级、又在生物课上接触过这个话题。她本不必太担心。然而，这是第一次，她感到事关自身。",
        "那个六月，科纳克里的太阳狠狠地烤着屋顶。马耶妮收拾东西。她刚写了两个小时，那些字眼比平时更锋利。她走向同学们躲荫的芒果树，手指微微发抖。",
        "阿伊莎：怎么样，马耶妮？你写了什么？你这个没『洗过』的人……你根本不知道做一个真正的女人是什么意思。",
        "别的女孩窃笑起来。马耶妮抬起眼。她准备好了说辞，但忽然觉得它们太渺小。",
        "马耶妮：老师一直说这是健康问题。我的身体是完整的。这并不改变我是谁。",
        "阿伊莎：书本上也许是。可在我们看来，你还是个孩子。",
        "人群笑着散去。马耶妮独自站了一会儿，盯着自己沾灰的鞋。胸口有什么东西揪紧了。并不完全是羞耻。是一种沉重，像一个没有答案的问题。",
        "回家的路上，妈妈做的花生酱福尼奥饭的香味也无法安慰她。一路上，嗤笑跟着她，还有阿伊莎的话：一辈子的孩子，对自己习俗的陌生人。她在客厅坐下，垂下头。难道父母保护了她的身体，就偷走了她的传承？她因为保持完整，就更不像几内亚人了吗？",
        "父亲等着他的小冠军讲讲这一天。迎接他的却是一堵沉默之墙。那天晚上，家里比平时更安静。那个总能让夜晚热闹起来的人一言不发。然后，忽然——",
        "马耶妮：妈妈、爸爸，你们为什么没让我接受割礼？在学校里，人家说我不属于我的文化。",
        "一阵漫长而沉重的沉默。母亲放下电脑。父亲放下杯子。他们相视。",
        "爸爸：谁跟你说的？",
        "马耶妮：所有人。不是用话，是用眼神。她们说要长大，就得经历刀的考验。你们为什么不为我做？",
        "沉默再次降临，更加沉重——那是意识到自己多年来一直回避这场谈话的父母的沉默。",
        "父亲斟酌着措辞：从前，人们相信这种痛苦是学会忍耐所必需的。母亲把哭泣的女儿紧紧搂在怀里。",
        "妈妈：马耶妮，很久以来，我们的社会都以为切割是进入传统的大门。许多女人因此痛苦了一生。我们决定让你的身体保持完整，因为你的价值不取决于一道伤口。但你说得对：你应得的是话语，我的心肝，而不只是我们的沉默。" ] },
      { id: "ch2", title: "第二章 — 芬达尼的抉择", paragraphs: [
        "夜幕已落。在女儿入睡很久之后，马耶妮的父母在厨房里低声交谈。他们保护了她的身体，却忘了准备她的心灵。",
        "沉默让位于分歧，再让位于求索。母亲态度坚决：不碰女孩的身体，但也不丢失自己的根。父亲既忧虑他人目光的分量，又拒绝那残忍的行为。",
        "爸爸：她说得对。我们替她免去了痛苦，却没免去排斥。这还不够。",
        "妈妈：我们拒绝痛苦是对的。但拒绝还不够：我们的孩子在两个世界之间长大，却没有人给他们另一条路。",
        "爸爸：那就由我们来给。",
        "母亲缓缓点头。她的眼中，有什么定了下来。",
        "妈妈：我们要创造属于我们自己的仪式。用言语取代刀。用知识取代切割。为此，我们必须去找那些懂的人……那些老人家。",
        "从僵局中诞生了决心。他们并不孤单。他们决定组织一次聚会，看看是否还有别的父母怀着同样的需要：一条不伤害女儿、在德行与健康中养育她们的路。",
        "那一夜，马耶妮的父母几乎没睡。他们写、计划、打电话。黎明时分，芬达尼已初具雏形。" ] },
      { id: "ch3", title: "第三章 — 回到根源", paragraphs: [
        "几天后，一个雨夜，聚会在女族长恩加·娜娜的客厅举行。一边，是坐在席子上的白发女人；另一边，是前来叩问传统的父母。气氛紧张，如同暴风雨来临之前。",
        "马耶妮的母亲：我们不是来评判你们的。你们曾是一场过渡、一场蜕变的守护者。我们想明白：在那行为的背后，你们真正传递的是什么？在刀占据一切之前，这仪式承载着怎样的秘密？",
        "年迈的恩加·娜娜看着自己布满皱纹的双手。她吸了口气，停顿良久，仿佛要潜入自己的回忆。",
        "恩加·娜娜：我们教导端庄。教导尊重自己与他人。教导那种看不见、却能在风暴中屹立不倒的力量。",
        "她停顿了一下。然后，更温柔地说：",
        "恩加·娜娜：但确实……随着岁月流逝，刀变得比言语更显眼。仿佛我们忘了它只是外壳，而仪式的核心，是别的东西。",
        "妈妈·耶丽：芬达尼给了我们一个机会，重新成为我们最初的样子：教育者，智慧的传递者，而不是暗处的『刀手』。",
        "白发的头一个个转向彼此。许久以来第一次，在那房间里，有某种温柔降临——像一场与自己的无声和解。" ] },
      { id: "ch4", title: "第四章 — 知识之夜", paragraphs: [
        "那一夜，在学校的院子里，天空晴朗。月亮像一位被宫女环绕的王后，那些星星以闪烁向她欢呼。院子中央燃起一堆火；火苗在温暖的空气中起舞。小女孩和少女们围成一圈。藏在枝叶后的鼓手与笛手奏响了序曲。老人家们站立着，手持瓦萨昆巴，开始了仪式。",
        "院子变了样。被称作『塞玛』的智慧长者们围着少女们。恩加·娜娜身着一袭洁白的长袍，头戴一顶饰有荆棘与海贝的红冠，举起她那镶着葫芦碎片的乐器，唱起净化灵魂之歌。",
        "♪ Nga wobé bira khi tokhogbi nè / An nkha sa a makha khoummawali ma…",
        "「恩加·沃贝掉进了鸡粪里／她要我在库玛瓦里河里给她洗澡……」",
        "女孩们齐声应和。即便被骂作『脏丫头』的人，也应得到尊重与照顾。",
        "恩加·娜娜：永远不要以外表评判一个人。真实，永远比表象更可贵。",
        "火苗噼啪升高。一只猫头鹰掠过繁星的夜空。恩加·娜娜的声音柔和下来，第二支歌升起，更缓、更温柔。是时候礼赞身体的完整了。妈妈·耶丽走向马耶妮，温柔地望着她。",
        "♪ A tofan deh m'ma diyorè tofan deh / A tofan deh diyorè fangni tofan deh…",
        "「我的宝贝多么美丽／我那肤色如乌木般温润的宝贝……她的双唇红艳，却不曾蘸过红油……」",
        "妈妈·耶丽：你们本就完美。你们的牙齿、皮肤、笑容、眼神。为什么要切去本已是珍宝的东西？",
        "马耶妮明白了，她的身体无需被『修正』。她本就是一颗珍宝，一根成熟的香蕉，体内蕴含着造化的全部光华。",
        "南登·南登随着鼓点跳了几步舞，然后端起一只盛满清水和取自圣林新鲜叶子的大葫芦，为少女们净手，唱起一首礼赞纯洁的颂歌。",
        "♪ Nga Yakha keli yo, nki Sali yé donkhoe nkha nya yarakha",
        "「雅卡妈妈，醒来吧，分一点你净身的水给我，让我洗净面庞。」",
        "马耶妮感到胸中某处松开了。仿佛她从校园里一直背负的那个结，终于解开了。",
        "为结束这一夜，塞玛们唱起商人之歌：女人的尊严如同一块珍贵的布巾，须以荣耀来佩戴。",
        "♪ Nfafé Youlai Nfafé Youlai Ayi ya ! / Nfafé Youlai dougui di ndé bé ayi ya !",
        "「哦，亲爱的商人，这里有一块崭新闪亮的布巾……人要端正仪态，才配得上它。」",
        "那一夜，女孩们学到的不只是歌。她们学会了认识自己：自己的权利、身体与历史。她们谈健康，谈尊重，谈一个人对自己应有的爱。老人家们讲了很久，女孩们聆听着，像长途跋涉后饮下清凉的水。" ] },
      { id: "ch5", title: "第五章 — 芬达尼的使者", paragraphs: [
        "黎明升起，玫瑰色与金色交织。火渐渐熄灭。围坐成圈的女孩们，眼里闪着疲惫，以及某种近乎自豪的光。她们一个接一个，领取了『芬达尼使者』的徽章。",
        "哈娃：马耶妮，从此你是知识的入门者。不是凭痛苦，而是凭领悟。你的斗争从这里开始，就在今晨，就在这院子里。它将走得很远。",
        "马耶妮双手捧着她的那块布巾、竹项链和入门者之杖。她想起阿伊莎。想起那夜站在厨房里的母亲。想起那些老妇人——在这么多年之后，选择了倾听与传承。",
        "马耶妮：谢谢你，哈娃。我不再羞愧。我是一个非洲女人，几内亚人，受过教育，完整而自由。",
        "在内心深处，马耶妮已不再是校园里那个困惑的小女孩。她是一名入门者。森林的秘密不在于刀刃，而在于那些教会她认识自己的旋律。",
        "而她的父母，为让女儿认识了森林而自豪。不是随便哪一片森林：而是一片树木低语秘密、而非发出哭喊的森林。",
        "别的女孩们齐声应和，先是轻轻地，然后越来越响，直到那些词语像鸟儿一样升入清晨的天空。在学校旁的森林里——那片古人曾称作『拉加』、即仪式之林的森林——那个早晨，再没有哭喊与泪水。只有歌唱的声音。" ] },
      { id: "epilogue", title: "尾声 — 绽放的森林", paragraphs: [
        "自那一夜起，别的校园也亮起来，别的篝火，别的歌声。从一个省到另一个省，女孩们以知识为盾、以尊严为冠地长大。",
        "因为文化是一棵树。它需要深扎的根，也需要向天空舒展的枝。它能蜕变而不死亡。它能传承而不伤人。",
        "「芬达尼：因为文化是一份以言语、而非以血来传递的财富。」",
        "马耶妮十三岁，有一个挥之不去的问题：人能否不经过刀，就归属于自己的族人？",
        "一个夜晚，在她学校的院子里，老人家们点起一堆火。今夜她们手中没有刀——只有歌声、净身的水，以及一段比痛苦更古老的仪式记忆。森林的秘密，马耶妮将以另一种方式学会。",
        "一个由法图玛塔·雅丽·西塞讲述的故事 — 巴提文集 · 团结工坊。" ] },
    ],
  },
};
