// Le Maître d'école — d'après le sketch de Fodéba Keïta (1952)
// Collection Pati — Aventure (10–12 ans)
// Lecteur multilingue : sections alignées fr / en / ar / zh
// RÈGLE BIBLE PATI : les noms propres sont INVARIANTS dans les 4 langues
//   (Damba, Pathé, Néné, Thierno, Mama Aïssata, Hawa Camara,
//    Fodéba Keïta, Djéli Mamoudou Kandé, Alpha Yaya Diallo, Pati,
//    Victor Hugo, Louis Pasteur, Conakry, Fouta — non traduits/translittérés).
// NB AR/ZH : à faire relire par un locuteur natif avant mise en production.

export type Lang = "fr" | "en" | "ar" | "zh";

export interface Section {
  id: number;
  title: Record<Lang, string>;
  body: Record<Lang, string[]>; // un tableau de paragraphes par langue, alignés
}

export const meta = {
  slug: "maitre-ecole",
  collection: "Pati Aventure",
  ageRange: "10-12",
  title: {
    fr: "Le Maître d'école",
    en: "The Schoolteacher",
    ar: "معلّم المدرسة",
    zh: "学校的老师",
  },
  subtitle: {
    fr: "Une histoire d'après le sketch de Fodéba Keïta",
    en: "A story after the sketch by Fodéba Keïta",
    ar: "قصة مستوحاة من مشهد فوديبا كيتا (Fodéba Keïta)",
    zh: "改编自 Fodéba Keïta 的短剧",
  },
  rtl: { fr: false, en: false, ar: true, zh: false },
};

export const sections: Section[] = [
  {
    id: 1,
    title: {
      fr: "La malle du fond",
      en: "The trunk at the back",
      ar: "الصندوق في آخر القاعة",
      zh: "教室角落的旧箱子",
    },
    body: {
      fr: [
        "Il pleuvait sur Conakry, et la kermesse était dans deux semaines.",
        "Au tableau de la classe de CM2, la Maîtresse Hawa Camara avait écrit trois mots : « Quelque chose de chez nous. »",
        "— Chaque groupe présente un numéro pour la kermesse, dit-elle. Pas un numéro copié sur un téléphone. Un numéro qui parle de nous.",
        "Pendant que les autres se disputaient entre playback et match de gala, Damba s'était glissée au fond, près de la vieille malle que personne n'ouvrait jamais. Elle souleva le couvercle. Ça sentait le papier mouillé et le temps.",
        "Tout en bas, un livre corné, un titre fatigué : Poèmes africains. Un nom dessous : Fodéba Keïta.",
        "Elle l'ouvrit au hasard, tomba sur une scène de théâtre, lut deux lignes. Puis elle éclata de rire, toute seule, au fond de la classe.",
        "— Damba ? fit la Maîtresse Hawa. Tu as trouvé ton numéro ?",
        "Damba leva le livre.",
        "— Je crois que oui, Maîtresse.",
      ],
      en: [
        "Rain was falling over Conakry, and the school fair was two weeks away.",
        "On the board of the final-year class, Maîtresse Hawa Camara had written three words: \"Something of our own.\"",
        "\"Each group performs an act for the fair,\" she said. \"Not something copied off a phone. An act that speaks of us.\"",
        "While the others argued over lip-syncing and a gala match, Damba had slipped to the back, near the old trunk nobody ever opened. She lifted the lid. It smelled of damp paper and time.",
        "Right at the bottom, a dog-eared book, a tired title: African Poems. A name beneath it: Fodéba Keïta.",
        "She opened it at random, landed on a theatre scene, read two lines. Then she burst out laughing, all alone at the back of the class.",
        "\"Damba?\" said Maîtresse Hawa. \"Have you found your act?\"",
        "Damba held up the book.",
        "\"I think I have, Maîtresse.\"",
      ],
      ar: [
        "كان المطر يهطل على Conakry، ولم يبقَ على حفل المدرسة سوى أسبوعين.",
        "على سبّورة الصف الأخير، كتبت Maîtresse Hawa Camara ثلاث كلمات: «شيءٌ من عندنا».",
        "قالت: «كل مجموعة تقدّم فقرة للحفل. لا فقرة منقولة عن الهاتف. فقرة تتحدّث عنّا.»",
        "بينما كان الآخرون يتجادلون بين الغناء المقلَّد ومباراة استعراضية، تسلّلت Damba إلى آخر القاعة، قرب الصندوق القديم الذي لا يفتحه أحد. رفعت الغطاء. كانت رائحته رائحة ورقٍ مبلَّل وزمنٍ قديم.",
        "في الأسفل تمامًا، كتابٌ مثنيّ الأطراف، عنوانٌ متعَب: «أشعار إفريقية». وتحته اسم: Fodéba Keïta.",
        "فتحته صدفةً، فوقعت على مشهد مسرحي، وقرأت سطرين. ثم انفجرت ضاحكةً وحدها في آخر الصف.",
        "قالت Maîtresse Hawa: «‏Damba؟ هل وجدتِ فقرتك؟»",
        "رفعت Damba الكتاب.",
        "«أظنّ ذلك يا Maîtresse.»",
      ],
      zh: [
        "雨下在 Conakry 城里，离学校的游园会只剩两个星期。",
        "在毕业班的黑板上，Maîtresse Hawa Camara 写下了三个词：「属于我们自己的东西。」",
        "「每个小组为游园会准备一个节目，」她说。「不是从手机上抄来的节目，而是一个讲述我们自己的节目。」",
        "当别人还在为对口型表演和表演赛争论时，Damba 悄悄溜到教室后面，走近那只谁也不打开的旧箱子。她掀开盖子，里面是一股潮湿纸张和岁月的气味。",
        "最底下压着一本卷了角的书，书名已经褪色：《非洲诗篇》。下面有个名字：Fodéba Keïta。",
        "她随手翻开，正翻到一幕戏剧，读了两行，便独自一人在教室后面笑出了声。",
        "「Damba？」Maîtresse Hawa 问，「你找到你的节目了吗？」",
        "Damba 举起那本书。",
        "「我想是的，Maîtresse。」",
      ],
    },
  },
  {
    id: 2,
    title: {
      fr: "Ce que disait le vieux livre",
      en: "What the old book said",
      ar: "ما كان يقوله الكتاب القديم",
      zh: "那本旧书讲的故事",
    },
    body: {
      fr: [
        "À la récréation, ils étaient quatre autour du livre : Damba, Pathé qui voulait déjà tous les rôles, Thierno le sceptique, et Néné qui s'était approchée sans rien dire.",
        "— C'est une scène d'école, expliqua Damba. Mais une école d'avant. Du temps où la Guinée n'était pas encore la Guinée.",
        "— L'école coloniale, dit Thierno. Un truc de grands-parents.",
        "— Écoute d'abord.",
        "Dans la scène, un maître interrogeait ses élèves. « Citez-moi un savant », demandait-il, très fier. Un élève répondait : « Victor Hugo ! » Un autre : « Louis Pasteur ! » Puis le maître demandait : « Et qu'est-ce qu'un savant ? » Et un petit élève, sérieux comme tout, répondait :",
        "— Le plus grand savant, maître… c'est vous.",
        "Pathé se tapa sur la cuisse.",
        "— Et le maître le corrige ?",
        "— Justement non, dit Damba. Il est si flatté qu'il laisse dire. Il se croit le plus grand savant du monde.",
        "— Ça, fit Thierno en regardant Pathé, je connais quelqu'un.",
        "Damba continua. Un élève arrivait en retard ; il revenait de fiançailles, où il avait dû chanter. Le maître oubliait la punition : « Chante-nous donc ça ! » Et toute la classe se mettait à chanter. La leçon était finie. Le chant avait gagné.",
        "Il y eut un silence.",
        "— C'est nous, dit doucement Néné. C'est nous, ça.",
      ],
      en: [
        "At break, four of them gathered around the book: Damba, Pathé who already wanted every role, Thierno the doubter, and Néné who had drawn near without a word.",
        "\"It's a school scene,\" Damba explained. \"But a school from before. From when Guinea wasn't yet Guinea.\"",
        "\"The colonial school,\" said Thierno. \"A grandparents' thing.\"",
        "\"Listen first.\"",
        "In the scene, a teacher questioned his pupils. \"Name me a scholar,\" he asked, very proud. One pupil answered: \"Victor Hugo!\" Another: \"Louis Pasteur!\" Then the teacher asked: \"And what is a scholar?\" And a small pupil, as serious as could be, answered:",
        "\"The greatest scholar, sir… is you.\"",
        "Pathé slapped his thigh.",
        "\"And does the teacher correct him?\"",
        "\"That's just it — no,\" said Damba. \"He's so flattered he lets it stand. He believes he's the greatest scholar in the world.\"",
        "\"That,\" said Thierno, looking at Pathé, \"reminds me of someone.\"",
        "Damba went on. A pupil arrived late; he was coming back from an engagement party, where he'd had to sing. The teacher forgot the punishment: \"Sing it for us, then!\" And the whole class began to sing. The lesson was over. The song had won.",
        "There was a silence.",
        "\"That's us,\" Néné said softly. \"That's us, right there.\"",
      ],
      ar: [
        "في الاستراحة، اجتمع أربعةٌ حول الكتاب: Damba، وPathé الذي كان يريد كل الأدوار، وThierno المتشكّك، وNéné التي اقتربت دون أن تنبس بكلمة.",
        "قالت Damba: «إنه مشهدٌ في مدرسة. لكنها مدرسة قديمة، من زمنٍ لم تكن فيه Guinée قد صارت Guinée بعد.»",
        "قال Thierno: «المدرسة الاستعمارية. شيءٌ يخصّ الأجداد.»",
        "«اسمع أولًا.»",
        "في المشهد، كان معلّمٌ يسأل تلاميذه: «سمّوا لي عالِمًا»، وهو فخورٌ جدًّا. أجاب تلميذ: «‏Victor Hugo!» وآخر: «‏Louis Pasteur!» ثم سأل المعلّم: «وما هو العالِم؟» فأجاب تلميذٌ صغير، بمنتهى الجدّية:",
        "«أعظم عالِم، يا أستاذ… هو أنت.»",
        "ضرب Pathé على فخذه.",
        "«وهل صحّح له المعلّم؟»",
        "قالت Damba: «هنا بالضبط… لا. كان مزهوًّا إلى حدّ أنه ترك الكلام يمرّ. صار يظنّ نفسه أعظم عالِمٍ في العالم.»",
        "قال Thierno وهو ينظر إلى Pathé: «هذا… أعرف شخصًا يشبهه.»",
        "تابعت Damba. تلميذٌ يصل متأخّرًا؛ كان عائدًا من حفل خطوبة غنّى فيه. فينسى المعلّم العقاب: «غنِّ لنا إذًا!» فيبدأ الصف كلّه بالغناء. انتهى الدرس. وانتصر الغناء.",
        "ساد صمت.",
        "قالت Néné بهدوء: «هذا نحن. هذا نحن بالضبط.»",
      ],
      zh: [
        "课间休息时，四个人围在书旁：Damba，已经想包揽所有角色的 Pathé，爱怀疑的 Thierno，还有一句话也没说就凑过来的 Néné。",
        "「这是一个学校里的场景，」Damba 解释道。「不过是从前的学校，那时候 Guinée 还不是今天的 Guinée。」",
        "「殖民时期的学校，」Thierno 说。「爷爷奶奶那辈的玩意儿。」",
        "「你先听。」",
        "在剧里，一位老师考问学生。「给我说出一位学者，」他得意洋洋地问。一个学生答：「Victor Hugo！」另一个答：「Louis Pasteur！」老师又问：「那么，什么是学者？」一个一脸认真的小学生答道：",
        "「最伟大的学者，老师……就是您。」",
        "Pathé 拍了一下大腿。",
        "「那老师纠正他了吗？」",
        "「问题就在这儿——没有，」Damba 说。「他太得意了，就由它去。他真以为自己是世界上最伟大的学者。」",
        "「这个嘛，」Thierno 看着 Pathé 说，「我倒认识一个。」",
        "Damba 继续讲。一个学生迟到了；他刚从一场订婚宴回来，在那儿得唱歌。老师忘了责罚：「那你就给我们唱唱看！」于是全班都唱了起来。课上不下去了。歌声赢了。",
        "一阵沉默。",
        "「这就是我们，」Néné 轻声说。「这说的就是我们。」",
      ],
    },
  },
  {
    id: 3,
    title: {
      fr: "Qui était ce monsieur ?",
      en: "Who was this man?",
      ar: "من كان هذا الرجل؟",
      zh: "这位先生是谁？",
    },
    body: {
      fr: [
        "Le problème, c'est que personne ne savait qui était Fodéba Keïta.",
        "Ce fut la grand-mère de Damba, Mama Aïssata, qui rangeait des arachides sous la véranda, qui leur ouvrit la vraie porte.",
        "— Fodéba ? Bien sûr. Vous croyez qu'il est mort, ce monsieur ?",
        "— Il est mort, Mama, dit Damba prudemment.",
        "— L'homme, oui. Mais regardez.",
        "Elle leva un doigt.",
        "— Les Ballets Africains, les danseurs qui font le tour du monde, qui dansent à Paris, à Tokyo. C'est lui. C'est Fodéba qui les a créés. Et ils tournent encore. Ce qu'il a planté, ça danse toujours.",
        "Thierno fronça les sourcils.",
        "— Donc c'est pas un truc mort. C'est un truc qui continue.",
        "— Tout ce qui est vivant continue, dit Mama Aïssata. Attendez. Il y a plus fort.",
      ],
      en: [
        "The trouble was, nobody knew who Fodéba Keïta was.",
        "It was Damba's grandmother, Mama Aïssata, sorting groundnuts under the veranda, who opened the real door for them.",
        "\"Fodéba? Of course. You think he's dead, that man?\"",
        "\"He is dead, Mama,\" said Damba carefully.",
        "\"The man, yes. But look.\"",
        "She raised a finger.",
        "\"Les Ballets Africains — the dancers who tour the world, who dance in Paris, in Tokyo. That's him. Fodéba created them. And they're still touring. What he planted is still dancing.\"",
        "Thierno frowned.",
        "\"So it's not a dead thing. It's a thing that keeps going.\"",
        "\"Everything alive keeps going,\" said Mama Aïssata. \"Wait. There's something stronger.\"",
      ],
      ar: [
        "المشكلة أن لا أحد كان يعرف من هو Fodéba Keïta.",
        "كانت جدّة Damba، Mama Aïssata، التي كانت تنقّي الفول السوداني تحت الشُّرفة، هي من فتحت لهم الباب الحقيقي.",
        "«‏Fodéba؟ بالطبع. أتظنّون أنه ميت، هذا الرجل؟»",
        "قالت Damba بحذر: «لقد مات يا Mama.»",
        "«الرجل، نعم. لكن انظروا.»",
        "رفعت إصبعها.",
        "«‏Les Ballets Africains، الراقصون الذين يجوبون العالم، الذين يرقصون في Paris وفي Tokyo. إنه هو. Fodéba هو من أنشأها. وما زالت تجوب العالم إلى اليوم. ما غرسه لا يزال يرقص.»",
        "قطّب Thierno حاجبيه.",
        "«إذًا ليس شيئًا ميتًا. إنه شيءٌ مستمرّ.»",
        "قالت Mama Aïssata: «كل ما هو حيّ يستمرّ. انتظروا. هناك ما هو أقوى.»",
      ],
      zh: [
        "问题在于，没人知道 Fodéba Keïta 是谁。",
        "是 Damba 的外婆 Mama Aïssata——正在屋檐下挑拣花生的她——为他们打开了真正的那扇门。",
        "「Fodéba？当然知道。你们以为这位先生死了吗？」",
        "「他是去世了，Mama，」Damba 小心地说。",
        "「人，是去世了。可你们看。」",
        "她竖起一根手指。",
        "「Les Ballets Africains——那些周游世界的舞者，在 Paris、在 Tokyo 演出的舞者。就是他。是 Fodéba 创办了他们。如今他们还在巡演。他种下的东西，至今仍在起舞。」",
        "Thierno 皱起眉头。",
        "「这么说，它不是死掉的东西。它是一直延续着的东西。」",
        "「凡是活着的，都会延续下去，」Mama Aïssata 说。「等等。还有更厉害的。」",
      ],
    },
  },
  {
    id: 4,
    title: {
      fr: "La chanson de chaque matin",
      en: "The song of every morning",
      ar: "أغنية كل صباح",
      zh: "每天早晨的那首歌",
    },
    body: {
      fr: [
        "— Tous les matins, à l'école, vous chantez quoi ? demanda Mama Aïssata.",
        "— L'hymne, dit Pathé. « Peuple d'Afrique ! Le passé historique… »",
        "— Et qui l'a fait, d'après vous ?",
        "Les quatre se regardèrent. Personne ne s'était jamais posé la question. On chante l'hymne comme on respire.",
        "— C'est lui, dit Mama Aïssata. C'est Fodéba qui a porté cet hymne. Le monsieur de votre vieux livre. Celui qui se moque du maître infatué a façonné la chanson que vous chantez la main sur le cœur.",
        "Thierno resta bouche bée. Lui, le sceptique. L'hymne, il le connaissait depuis la maternelle. Il l'avait dans la bouche depuis toujours.",
        "— Mais il l'a inventé tout seul, l'air ? demanda Damba.",
        "Mama Aïssata sourit. C'était la question qu'elle attendait.",
        "— Non. Et c'est là que c'est beau. Asseyez-vous.",
      ],
      en: [
        "\"Every morning at school, what do you sing?\" asked Mama Aïssata.",
        "\"The anthem,\" said Pathé. \"People of Africa! The historic past…\"",
        "\"And who made it, do you think?\"",
        "The four looked at one another. None of them had ever asked. You sing the anthem the way you breathe.",
        "\"It's him,\" said Mama Aïssata. \"Fodéba is the one who carried that anthem. The man from your old book. The one who mocks the puffed-up teacher shaped the song you sing with your hand on your heart.\"",
        "Thierno's jaw dropped. Him, the doubter. He'd known the anthem since nursery school. It had been in his mouth forever.",
        "\"But did he invent the tune all by himself?\" asked Damba.",
        "Mama Aïssata smiled. That was the question she'd been waiting for.",
        "\"No. And that's where it gets beautiful. Sit down.\"",
      ],
      ar: [
        "سألت Mama Aïssata: «كل صباح في المدرسة، ماذا تغنّون؟»",
        "قال Pathé: «النشيد. ‹يا شعب إفريقيا! أيها الماضي العريق…›»",
        "«ومن صنعه، في ظنّكم؟»",
        "نظر الأربعة بعضهم إلى بعض. لم يسأل أحدٌ منهم هذا السؤال قط. نحن نغنّي النشيد كما نتنفّس.",
        "قالت Mama Aïssata: «إنه هو. Fodéba هو من حمل هذا النشيد. الرجل صاحب كتابكم القديم. الذي يسخر من المعلّم المغرور هو من صاغ الأغنية التي تغنّونها واضعين أيديكم على قلوبكم.»",
        "بقي Thierno فاغرًا فاه. هو، المتشكّك. كان يعرف النشيد منذ الروضة. كان في فمه منذ الأزل.",
        "سألت Damba: «لكن، هل ألّف اللحن وحده؟»",
        "ابتسمت Mama Aïssata. كان هذا هو السؤال الذي تنتظره.",
        "«لا. وهنا يكمن الجمال. اجلسوا.»",
      ],
      zh: [
        "「每天早晨在学校，你们唱什么？」Mama Aïssata 问。",
        "「国歌，」Pathé 说。「『非洲人民！光辉的往昔……』」",
        "「那你们觉得，是谁谱写的？」",
        "四个人面面相觑。谁也没问过这个问题。唱国歌就像呼吸一样自然。",
        "「就是他，」Mama Aïssata 说。「是 Fodéba 把这首国歌扛了起来。就是你们那本旧书里的先生。那个嘲笑自负老师的人，谱写了你们手按胸口唱的那首歌。」",
        "Thierno 张大了嘴。他，那个爱怀疑的人。国歌他从幼儿园起就会唱，它一直挂在他嘴边。",
        "「可这曲子是他一个人想出来的吗？」Damba 问。",
        "Mama Aïssata 笑了。这正是她等着的问题。",
        "「不是。而这正是动人之处。坐下吧。」",
      ],
    },
  },
  {
    id: 5,
    title: {
      fr: "La chaîne",
      en: "The chain",
      ar: "السلسلة",
      zh: "这条链子",
    },
    body: {
      fr: [
        "— L'air de notre hymne est plus vieux que Fodéba, dit Mama Aïssata. Plus vieux que moi.",
        "Elle compta sur ses doigts.",
        "— Fodéba l'a arrangé pour qu'il devienne l'hymne du pays. Avant lui, un grand griot l'avait retravaillé : Djéli Mamoudou Kandé. Et lui-même ne l'avait pas inventé. Cet air, on le chantait déjà là-haut, au Fouta. Une louange pour honorer un homme qui avait tenu tête aux colons : Alpha Yaya Diallo.",
        "— Donc la chanson du matin, dit lentement Thierno…",
        "— … vient d'un chant de griot pour un résistant. De bouche en bouche. D'un griot à Fodéba. De Fodéba à votre école. Et de votre école à vous.",
        "Damba compta dans sa tête. Plus de cent ans, de voix en voix, jusqu'à eux.",
        "— Alors le maître de la scène se trompe, dit-elle. Le savoir, ce n'est pas que les livres et lui-même.",
        "— Il ne se trompe pas tout à fait. Les livres, c'est du savoir. Mais pas tout le savoir. Celui qui dure le plus longtemps chez nous ne s'écrit pas toujours : il se chante, il se transmet. Et personne ne peut se dire le plus grand savant, parce que personne n'est au bout de la chaîne. On est tous un maillon.",
        "Néné, sans s'en rendre compte, fredonnait déjà l'air de l'hymne.",
      ],
      en: [
        "\"The tune of our anthem is older than Fodéba,\" said Mama Aïssata. \"Older than me.\"",
        "She counted on her fingers.",
        "\"Fodéba arranged it so it could become the country's anthem. Before him, a great griot had reworked it: Djéli Mamoudou Kandé. And he hadn't invented it either. That tune was already sung up there, in the Fouta. A praise song to honour a man who had stood up to the colonisers: Alpha Yaya Diallo.\"",
        "\"So the morning song,\" Thierno said slowly…",
        "\"…comes from a griot's song for a resister. From mouth to mouth. From a griot to Fodéba. From Fodéba to your school. And from your school to you.\"",
        "Damba counted in her head. More than a hundred years, from voice to voice, all the way to them.",
        "\"So the teacher in the scene is wrong,\" she said. \"Knowledge isn't just books and himself.\"",
        "\"He's not entirely wrong. Books are knowledge. But not all of it. The kind that lasts longest with us isn't always written down: it's sung, it's passed on. And no one can call themselves the greatest scholar, because no one is at the end of the chain. We're all a link.\"",
        "Néné, without realising it, was already humming the tune of the anthem.",
      ],
      ar: [
        "قالت Mama Aïssata: «لحن نشيدنا أقدم من Fodéba. أقدم منّي.»",
        "عدّت على أصابعها.",
        "«‏Fodéba نسّقه ليصير نشيد البلاد. وقبله، أعاد صياغته قَوّالٌ (غريو) كبير: Djéli Mamoudou Kandé. وهو نفسه لم يخترعه. هذا اللحن كان يُغنّى هناك في الأعلى، في Fouta. مديحٌ لتكريم رجلٍ وقف في وجه المستعمِرين: Alpha Yaya Diallo.»",
        "قال Thierno ببطء: «إذًا أغنية الصباح…»",
        "«…أصلها أغنية قَوّالٍ لمقاوِم. من فمٍ إلى فم. من قَوّالٍ إلى Fodéba. ومن Fodéba إلى مدرستكم. ومن مدرستكم إليكم.»",
        "عدّت Damba في رأسها. أكثر من مئة عام، من صوتٍ إلى صوت، حتى وصلت إليهم.",
        "قالت: «إذًا فمعلّم المشهد مخطئ. المعرفة ليست الكتب وذاته فحسب.»",
        "«ليس مخطئًا تمامًا. الكتب معرفة. لكنها ليست كل المعرفة. أبقى المعارف عندنا لا تُكتب دائمًا: تُغنّى وتُتوارث. ولا أحد يستطيع أن يسمّي نفسه أعظم عالِم، لأن لا أحد في نهاية السلسلة. كلّنا حلقة.»",
        "وكانت Néné، دون أن تدري، تدندن لحن النشيد.",
      ],
      zh: [
        "「我们国歌的曲调比 Fodéba 还老，」Mama Aïssata 说。「比我还老。」",
        "她掰着手指数。",
        "「Fodéba 把它改编，让它成了国家的国歌。在他之前，一位伟大的格里奥（说唱艺人）把它重新打磨过：Djéli Mamoudou Kandé。而他自己也不是它的发明者。这支曲子，早就在北方的 Fouta 唱开了。那是一首赞歌，用来颂扬一个曾抵抗殖民者的人：Alpha Yaya Diallo。」",
        "「这么说，早晨那首歌，」Thierno 慢慢地说……",
        "「……来自一位格里奥为一名抵抗者唱的歌。口口相传。从一位格里奥传到 Fodéba。从 Fodéba 传到你们的学校。再从你们的学校传到你们。」",
        "Damba 在心里数着。一百多年，一个声音传给一个声音，一直传到他们这里。",
        "「这么说，剧里的老师错了，」她说。「知识不只是书本，也不只是他自己。」",
        "「他也不全错。书本是知识，但不是全部的知识。在我们这里最长久的那种知识，并不总是写下来的：它被唱出来，被传下去。没有谁能自称最伟大的学者，因为没有谁站在这条链子的末端。我们都是其中一环。」",
        "Néné 不知不觉地，已经哼起了国歌的曲调。",
      ],
    },
  },
  {
    id: 6,
    title: {
      fr: "La répétition qui dérape",
      en: "The rehearsal that goes wrong",
      ar: "البروفة التي انحرفت",
      zh: "走了样的排练",
    },
    body: {
      fr: [
        "Ils se partagèrent les rôles. Pathé serait le maître infatué — évidemment. Thierno et Damba, les élèves qui citent Hugo et Pasteur. Et l'élève qui chante, ce serait Néné.",
        "— Moi ? Devant tout le monde ? Non.",
        "— C'est toi qui chantes le mieux, dit Damba. Tu chantes même sans t'en apercevoir.",
        "Néné baissa les yeux. Mais elle ne dit pas non.",
        "Les répétitions commencèrent. Et Pathé, dans le rôle du maître, prit goût à donner des ordres.",
        "— Non, Thierno, mets-toi là. Damba, tu parles trop fort. Néné, tu entres quand je le dis.",
        "— Pathé, c'est une répétition. Tu n'es pas vraiment le maître.",
        "— Mais c'est mon rôle ! Je suis le plus grand savant de la pièce !",
        "Il l'avait dit pour rire. Mais il l'avait dit. Et il y eut un silence gêné, parce que tout le monde entendit l'écho. Le plus grand savant, c'est vous, maître.",
        "— Pathé, dit Thierno doucement. Tu es en train de devenir le maître. Le vrai. Celui dont on se moque.",
        "Pathé ouvrit la bouche. La referma. Regarda ses mains comme si elles ne lui appartenaient plus.",
      ],
      en: [
        "They shared out the roles. Pathé would be the puffed-up teacher — of course. Thierno and Damba, the pupils who name Hugo and Pasteur. And the pupil who sings would be Néné.",
        "\"Me? In front of everyone? No.\"",
        "\"You sing the best,\" said Damba. \"You sing without even noticing.\"",
        "Néné looked down. But she didn't say no.",
        "Rehearsals began. And Pathé, in the teacher's role, took a liking to giving orders.",
        "\"No, Thierno, stand there. Damba, you're too loud. Néné, you come in when I say so.\"",
        "\"Pathé, it's a rehearsal. You're not really the teacher.\"",
        "\"But it's my role! I'm the greatest scholar in the play!\"",
        "He'd said it as a joke. But he'd said it. And an awkward silence fell, because everyone heard the echo. The greatest scholar, sir, is you.",
        "\"Pathé,\" said Thierno gently. \"You're turning into the teacher. The real one. The one we're laughing at.\"",
        "Pathé opened his mouth. Closed it. Looked at his hands as if they were no longer his.",
      ],
      ar: [
        "اقتسموا الأدوار. سيكون Pathé هو المعلّم المغرور — بالطبع. وThierno وDamba التلميذين اللذين يذكران Hugo وPasteur. أما التلميذة التي تغنّي فستكون Néné.",
        "«أنا؟ أمام الجميع؟ لا.»",
        "قالت Damba: «أنت أفضل من يغنّي. تغنّين دون أن تنتبهي حتى.»",
        "أطرقت Néné. لكنها لم تقل لا.",
        "بدأت البروفات. وراق لـ Pathé، في دور المعلّم، أن يُصدر الأوامر.",
        "«لا يا Thierno، قف هناك. Damba، صوتك عالٍ أكثر من اللازم. Néné، تدخلين حين أقول.»",
        "«‏Pathé، هذه بروفة. لست المعلّم حقًّا.»",
        "«لكنه دوري! أنا أعظم عالِمٍ في المسرحية!»",
        "قالها مازحًا. لكنه قالها. وساد صمتٌ محرج، لأن الجميع سمعوا الصدى: أعظم عالِم، يا أستاذ، هو أنت.",
        "قال Thierno بهدوء: «‏Pathé، أنت تتحوّل إلى المعلّم. المعلّم الحقيقي. الذي نسخر منه.»",
        "فتح Pathé فمه. أطبقه. نظر إلى يديه كأنهما لم تعودا له.",
      ],
      zh: [
        "他们分了角色。Pathé 演那个自负的老师——这是当然。Thierno 和 Damba 演说出 Hugo 和 Pasteur 的学生。那个唱歌的学生，就由 Néné 来演。",
        "「我？当着所有人的面？不行。」",
        "「你唱得最好，」Damba 说。「你唱起来自己都没察觉。」",
        "Néné 低下头。可她没有说不。",
        "排练开始了。演老师的 Pathé，渐渐迷上了发号施令。",
        "「不对，Thierno，站那儿。Damba，你声音太大。Néné，我说了你才能进来。」",
        "「Pathé，这是排练。你又不是真的老师。」",
        "「可这是我的角色！我可是这出戏里最伟大的学者！」",
        "他本是开玩笑。可他到底说了。一阵尴尬的沉默落下，因为人人都听见了那回声：最伟大的学者，老师，就是您。",
        "「Pathé，」Thierno 轻声说。「你正在变成那个老师。真的那个。我们正在嘲笑的那个。」",
        "Pathé 张了张嘴，又闭上，望着自己的双手，仿佛它们已不再属于他。",
      ],
    },
  },
  {
    id: 7,
    title: {
      fr: "La voix de Néné",
      en: "Néné's voice",
      ar: "صوت Néné",
      zh: "Néné 的歌声",
    },
    body: {
      fr: [
        "La répétition était cassée. Pathé boudait dans un coin, vexé d'avoir été pris pour celui qu'il jouait.",
        "Alors Néné fit une chose que personne n'attendait. Elle se mit à chanter.",
        "Pas l'hymne. Une vieille berceuse de sa mère, une mélodie qui montait et descendait comme la pluie sur les toits. D'abord tout bas. Puis un peu plus fort, parce que personne ne l'arrêtait.",
        "Un par un, ils se turent pour l'écouter. Même Pathé releva la tête. La colère, la vexation, la dispute — tout glissa et s'en alla, comme dans la scène du vieux livre, où la leçon s'efface devant le chant.",
        "Quand Néné s'arrêta, Damba dit tout bas :",
        "— C'est ça, le numéro. On ne joue pas la pièce. On est la pièce.",
        "Pathé se leva.",
        "— Je recommence. Mais cette fois, je joue un maître qui se croit grand. Je ne deviens pas un maître qui se croit grand. Tu vois la différence ?",
        "— Je vois, dit Damba. Maintenant, oui.",
      ],
      en: [
        "The rehearsal was broken. Pathé sulked in a corner, stung at being mistaken for the one he was playing.",
        "Then Néné did something no one expected. She began to sing.",
        "Not the anthem. An old lullaby of her mother's, a melody that rose and fell like rain on the rooftops. Softly at first. Then a little louder, because no one stopped her.",
        "One by one, they fell silent to listen. Even Pathé raised his head. The anger, the hurt, the quarrel — it all slipped away, just like in the old book's scene, where the lesson fades before the song.",
        "When Néné stopped, Damba said quietly:",
        "\"That's the act. We don't perform the play. We are the play.\"",
        "Pathé stood up.",
        "\"I'll start over. But this time, I play a teacher who thinks he's great. I don't become a teacher who thinks he's great. You see the difference?\"",
        "\"I see it,\" said Damba. \"Now I do.\"",
      ],
      ar: [
        "انهارت البروفة. اعتزل Pathé في زاوية مكتئبًا، موجوعًا لأنهم حسبوه ذاك الذي يؤدّي دوره.",
        "عندئذٍ فعلت Néné ما لم يتوقّعه أحد. بدأت تغنّي.",
        "ليس النشيد. تهويدة قديمة من تهويدات أمّها، لحنٌ يعلو ويهبط كالمطر على السطوح. بصوتٍ خفيض أولًا. ثم أعلى قليلًا، لأن لا أحد أوقفها.",
        "واحدًا تلو الآخر، صمتوا ليُصغوا. حتى Pathé رفع رأسه. الغضب، والجرح، والشِّجار — كل ذلك انزلق وذهب، كما في مشهد الكتاب القديم، حيث يتلاشى الدرس أمام الغناء.",
        "حين توقّفت Néné، قالت Damba بهدوء:",
        "«هذه هي الفقرة. نحن لا نمثّل المسرحية. نحن المسرحية.»",
        "نهض Pathé.",
        "«سأبدأ من جديد. لكن هذه المرة، أمثّل معلّمًا يظنّ نفسه عظيمًا. لا أتحوّل إلى معلّمٍ يظنّ نفسه عظيمًا. أترين الفرق؟»",
        "قالت Damba: «أراه. الآن، نعم.»",
      ],
      zh: [
        "排练散了架。Pathé 在角落里生着闷气，为被人当成了他所扮演的那个人而恼火。",
        "这时 Néné 做了一件谁也没料到的事。她唱了起来。",
        "不是国歌。是她母亲的一支古老摇篮曲，旋律像屋顶上的雨一样起起落落。起初很轻，后来稍稍响了些，因为没人去拦她。",
        "他们一个接一个安静下来听。连 Pathé 也抬起了头。愤怒、委屈、争吵——全都悄悄溜走了，就像那本旧书里的场景，课在歌声面前消散。",
        "Néné 停下时，Damba 低声说：",
        "「这才是我们的节目。我们不是在演这出戏。我们就是这出戏。」",
        "Pathé 站了起来。",
        "「我重来一遍。但这一回，我是在『演』一个自以为了不起的老师。我不是『变成』一个自以为了不起的老师。你看出区别了吗？」",
        "「我看出来了，」Damba 说。「现在看出来了。」",
      ],
    },
  },
  {
    id: 8,
    title: {
      fr: "La kermesse",
      en: "The school fair",
      ar: "حفل المدرسة",
      zh: "游园会",
    },
    body: {
      fr: [
        "Le jour de la kermesse, la cour était pleine : des bancs, des nattes, des parents, l'odeur des beignets et du gingembre glacé.",
        "Pathé joua son maître infatué à la perfection — pédant, bouffi, ridicule. Le public riait. Thierno citait Victor Hugo avec un sérieux énorme. Damba proposait Pasteur. Et quand vint la réplique — « Le plus grand savant, maître, c'est vous ! » — toute la cour éclata, parce que chacun connaissait un Pathé quelque part.",
        "Puis Néné entra. L'élève en retard.",
        "— Je revenais d'une fête de famille, maître. Je devais chanter.",
        "— Eh bien… chante !",
        "Et Néné chanta. Pas la berceuse : l'air de l'hymne, mais doucement, lentement, comme une louange — comme on devait le chanter au Fouta il y a cent ans, quand ce n'était encore qu'un chant de griot pour un homme courageux.",
        "Dans la cour, les parents reconnurent l'air. Les voix montèrent, une à une. Mama Aïssata chantait. La Maîtresse Hawa chantait.",
        "Pathé, dans son rôle, aurait pu interrompre, ramener l'ordre, faire la leçon. C'est ce que faisait l'instituteur du vieux livre.",
        "Il ne le fit pas. Il posa sa fausse règle de maître. Et il chanta avec les autres.",
      ],
      en: [
        "On the day of the fair, the schoolyard was full: benches, mats, parents, the smell of fritters and iced ginger.",
        "Pathé played his puffed-up teacher to perfection — pompous, swollen, ridiculous. The crowd laughed. Thierno named Victor Hugo with enormous seriousness. Damba offered Pasteur. And when the line came — \"The greatest scholar, sir, is you!\" — the whole yard burst out, because everyone knew a Pathé somewhere.",
        "Then Néné came in. The late pupil.",
        "\"I was coming back from a family party, sir. I had to sing.\"",
        "\"Well then… sing!\"",
        "And Néné sang. Not the lullaby: the tune of the anthem, but softly, slowly, like a praise song — the way it must have been sung in the Fouta a hundred years ago, when it was still just a griot's song for a brave man.",
        "In the yard, the parents recognised the tune. The voices rose, one by one. Mama Aïssata was singing. Maîtresse Hawa was singing.",
        "Pathé, in his role, could have interrupted, restored order, given the lesson. That's what the teacher in the old book did.",
        "He didn't. He set down his teacher's fake ruler. And he sang with the others.",
      ],
      ar: [
        "في يوم الحفل، امتلأت ساحة المدرسة: مقاعد، وحُصُر، وأهالٍ، ورائحة الفطائر والزنجبيل المثلَّج.",
        "أدّى Pathé معلّمه المغرور بإتقان — متحذلقًا، منتفخًا، مضحكًا. ضحك الجمهور. ذكر Thierno اسم Victor Hugo بجدّية بالغة. واقترحت Damba اسم Pasteur. وحين جاءت الجملة — «أعظم عالِم، يا أستاذ، هو أنت!» — انفجرت الساحة كلها ضحكًا، لأن كلّ واحدٍ يعرف Pathé ما في مكانٍ ما.",
        "ثم دخلت Néné. التلميذة المتأخّرة.",
        "«كنت عائدةً من حفل عائلي، يا أستاذ. كان عليّ أن أغنّي.»",
        "«حسنًا… غنّي!»",
        "فغنّت Néné. ليس التهويدة: بل لحن النشيد، لكن بهدوء وببطء، كأنه مديح — كما كان يُغنّى في Fouta قبل مئة عام، حين كان ما يزال مجرّد أغنية قَوّالٍ لرجلٍ شجاع.",
        "في الساحة، عرف الأهالي اللحن. ارتفعت الأصوات، واحدًا تلو الآخر. كانت Mama Aïssata تغنّي. وكانت Maîtresse Hawa تغنّي.",
        "كان بوسع Pathé، في دوره، أن يقاطع، وأن يعيد النظام، وأن يُلقي الدرس. هذا ما فعله معلّم الكتاب القديم.",
        "لكنه لم يفعل. وضع مسطرة المعلّم المزيّفة. وغنّى مع الآخرين.",
      ],
      zh: [
        "游园会那天，校园里挤满了人：长凳、草席、家长，还有油炸糕和冰镇姜汁的香味。",
        "Pathé 把那个自负的老师演得淋漓尽致——卖弄、自大、滑稽可笑。观众哈哈大笑。Thierno 一本正经地说出 Victor Hugo。Damba 提出 Pasteur。当那句台词出现时——「最伟大的学者，老师，就是您！」——全场哄堂大笑，因为人人身边都认得一个 Pathé。",
        "随后 Néné 上场了。那个迟到的学生。",
        "「我刚从一场家庭聚会回来，老师。我得唱歌。」",
        "「那好……唱吧！」",
        "于是 Néné 唱了。不是那支摇篮曲：是国歌的曲调，却轻轻地、缓缓地，像一首赞歌——就像一百年前在 Fouta 唱它的样子，那时它还只是一位格里奥献给一个勇者的歌。",
        "院子里，家长们认出了这支曲子。歌声一个接一个响起。Mama Aïssata 在唱。Maîtresse Hawa 在唱。",
        "Pathé 在他的角色里，本可以打断，重整秩序，开始上课。那本旧书里的老师就是这么做的。",
        "他没有。他放下了老师手里那把假尺子。他和大家一起唱了起来。",
      ],
    },
  },
  {
    id: 9,
    title: {
      fr: "Après",
      en: "Afterwards",
      ar: "بعد ذلك",
      zh: "之后",
    },
    body: {
      fr: [
        "Le soir, en rangeant le vieux livre, Damba hésita. Elle ne le remit pas tout au fond de la malle. Elle le posa sur l'étagère, à hauteur d'enfant, là où quelqu'un d'autre le trouverait.",
        "— Tu sais quoi ? dit Thierno. Au début, je croyais que c'était un truc mort. Un truc de grands-parents.",
        "— Et maintenant ?",
        "Thierno réfléchit.",
        "— Maintenant je crois que rien n'est mort, tant que quelqu'un le chante encore.",
        "Néné sourit. Elle fredonnait déjà autre chose.",
        "Et sur le mur de la classe, comme une ombre douce — une silhouette de conteuse, une mémoire qu'on devine plus qu'on ne voit — Pati veillait sur la chaîne qui continuait.",
        "Un maillon de plus venait d'être ajouté.",
      ],
      en: [
        "That evening, putting the old book away, Damba hesitated. She didn't return it to the bottom of the trunk. She set it on the shelf, at a child's height, where someone else would find it.",
        "\"You know what?\" said Thierno. \"At first I thought it was a dead thing. A grandparents' thing.\"",
        "\"And now?\"",
        "Thierno thought about it.",
        "\"Now I think nothing is dead, as long as someone still sings it.\"",
        "Néné smiled. She was already humming something else.",
        "And on the classroom wall, like a soft shadow — the silhouette of a storyteller, a memory more sensed than seen — Pati watched over the chain that went on.",
        "One more link had just been added.",
      ],
      ar: [
        "في المساء، وبينما كانت Damba تعيد الكتاب القديم إلى مكانه، ترددت. لم تُعِده إلى قاع الصندوق. وضعته على الرفّ، في ارتفاع طفل، حيث يجده شخصٌ آخر.",
        "قال Thierno: «أتعلمين؟ في البداية ظننته شيئًا ميتًا. شيئًا يخصّ الأجداد.»",
        "«والآن؟»",
        "فكّر Thierno.",
        "«الآن أظنّ أن لا شيء يموت، ما دام أحدٌ ما يغنّيه.»",
        "ابتسمت Néné. كانت تدندن شيئًا آخر بالفعل.",
        "وعلى جدار الصف، كظلٍّ رقيق — كطيف حكواتية، كذاكرةٍ تُحَسّ أكثر مما تُرى — كانت Pati تسهر على السلسلة المستمرّة.",
        "كانت حلقةٌ أخرى قد أُضيفت لتوّها.",
      ],
      zh: [
        "傍晚，Damba 收起那本旧书时犹豫了。她没有把它放回箱子最底下。她把它摆在书架上，孩子伸手就够得到的高度，好让别的人也能找到它。",
        "「你知道吗？」Thierno 说。「一开始我以为这是个死掉的东西。爷爷奶奶那辈的玩意儿。」",
        "「那现在呢？」",
        "Thierno 想了想。",
        "「现在我觉得，只要还有人在唱它，就没有什么是死的。」",
        "Néné 笑了。她已经在哼别的曲子了。",
        "而在教室的墙上，像一道柔和的影子——一个讲故事人的轮廓，一段与其说看见、不如说感觉到的记忆——Pati 守望着这条延续下去的链子。",
        "又一环，刚刚被接了上去。",
      ],
    },
  },
];
