/* ============================================================
   LA CARTE DES COMPAGNONS — données du jeu
   Jeu cartographique mémoire de Guinée · partenariat SENAG
   Inspiré du Défi des préfectures (même moteur carte).

   STRUCTURE : window.COMPAGNONS_DATA = { meta, compagnons[], femmes[] }
   - prefecture : doit correspondre au nom du tracé sur la carte (clé de placement)
   - circonscription1957 : libellé historique (peut différer du découpage actuel)
   - nom : graphie de référence du Compagnon
   - role : fonction/indice court (fiche mémoire + niveau 1)
   - indice : phrase d'indice (niveau 1 : nom donné → trouver la carte)
   - leurres : noms proposés comme distracteurs (niveau 2 : carte → trouver le nom)
   - source : "1957" (députés) | "croix1959" (Croix du Compagnon)
   - valide : true = attesté ; false = [À VALIDER] avant diffusion

   ⚠️ DOCUMENT DE TRAVAIL — vérification finale recommandée au
   Journal officiel de la Guinée française (avril 1957) et via
   Sidiki Kobélé Kéita (Esquisses biographiques) avant publication.
   ============================================================ */

window.COMPAGNONS_DATA = {
  meta: {
    titre: "La Carte des Compagnons",
    sousTitre: "Ceux et celles qui ont porté l'indépendance",
    partenaire: "SENAG — Semaine Nationale des Archives de Guinée",
    base: "Conseillers territoriaux élus le 31 mars 1957, devenus constituants le 2 octobre 1958 ; complétés par la Croix du Compagnon de l'Indépendance (1959-1960).",
    avertissement: "Document commémoratif. Présente le moment fondateur 1957-1958. Données à vérifier au Journal officiel avant publication définitive.",
    niveaux: {
      1: "Découverte — le nom et l'indice sont donnés, place le Compagnon sur sa circonscription.",
      2: "Mémoire — une circonscription s'éclaire, retrouve le Compagnon parmi plusieurs propositions."
    }
  },

  /* --- JEU PRINCIPAL : une figure emblématique par circonscription --- */
  compagnons: [
    { prefecture: "Beyla",       circonscription1957: "Beyla",       nom: "Célestine Robert",            role: "1er Vice-président de l'Assemblée nationale", fiche: "1er Vice-président de l'Assemblée nationale constituante, élu(e) de Beyla en 1957. Figure du bureau qui porta la naissance de l'État guinéen.", indice: "1er Vice-président de l'Assemblée, élu(e) de Beyla.", leurres: ["Cissé Moustapha", "Fofana Kéfimba", "Béavogui Koman"], tous: [{ nom: "Célestine Robert", source: "1957" }, { nom: "Cissé Moustapha", source: "1957" }, { nom: "Fofana Kéfimba dit Donzo Kéfing", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Boké",        circonscription1957: "Boké",        nom: "Camara Sankoumba",           role: "Conseiller territorial de Boké", fiche: "Conseiller territorial de Boké en 1957, la porte de la Basse-Côte au bord du Rio Nunez, ancienne place forte de l'histoire de la Guinée.", indice: "Conseiller territorial de la porte de la Basse-Côte, au bord du Rio Nunez.", leurres: ["Camara Mustapha", "Sako Moussa", "Touré Bakary"], tous: [{ nom: "Camara Sankoumba", source: "1957" }, { nom: "Camara Mustapha", source: "1957" }, { nom: "Camara Moustapha (député)", source: "croix1959" }, { nom: "Sako Moussa (Dioula)", source: "croix1959" }, { nom: "Touré Bakary (Dioula)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Conakry",     circonscription1957: "Conakry",     nom: "Ahmed Sékou Touré",          role: "Chef du PDG · élu de Conakry · futur Président de la République", indice: "Chef du PDG et élu de Conakry, il deviendra le premier Président de la Guinée.", fiche: "Leader du Parti Démocratique de Guinée (PDG), syndicaliste, élu de Conakry. Porté par le NON au référendum du 28 septembre 1958, il proclame l'indépendance le 2 octobre 1958 et devient le premier Président de la République de Guinée.", chefDeParti: "Parti Démocratique de Guinée (PDG)", leurres: ["Soumah Moustapha", "Fodéba Keïta", "Diallo Saïfoulaye"], tous: [{ nom: "Soumah Moustapha", source: "1957" }, { nom: "Ahmed Sékou Touré", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Dabola",      circonscription1957: "Dabola (cercle de Kolo)", nom: "Barry Diawadou",      role: "Chef du Bloc Africain de Guinée (BAG) · né à Kolo (Dabola)", indice: "Chef du BAG, né à Kolo près de Dabola : l'un des trois grands leaders de partis de 1958.", fiche: "Né en 1917 à Kolo (Dabola), de la lignée Soriya du Fouta. Chef du Bloc Africain de Guinée (BAG), parti longtemps d'une ligne modérée. Il se rallia au NON lors du référendum de 1958, aux côtés du PDG. Premier ministre de l'Éducation nationale du pays indépendant.", chefDeParti: "Bloc Africain de Guinée (BAG)", leurres: ["Barry Baba Alimou", "Barry Alpha Oumar", "Condé Ansoumane"], tous: [{ nom: "Barry Baba Alimou", source: "1957" }], source: "histoire", valide: true },
    { prefecture: "Dalaba",      circonscription1957: "Dalaba",      nom: "Bah Thierno Ibrahima",       role: "Conseiller territorial de Dalaba", fiche: "Conseiller territorial de Dalaba en 1957, dans les hauteurs du Fouta-Djalon.", indice: "Conseiller territorial de Dalaba, dans le Fouta.", leurres: ["Bah Thierno Ousmane", "Barry Mamadou Diouldé", "Sow Souleymane"], tous: [{ nom: "Bah Thierno Ibrahima", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Dinguiraye",  circonscription1957: "Dinguiraye",  nom: "Tall Mody Habidou",          role: "Élu de Dinguiraye · héritier de la cité d'El Hadj Omar Tall", indice: "Élu de Dinguiraye, la cité sainte fondée par El Hadj Omar Tall.", fiche: "Élu de Dinguiraye en 1957, seul indépendant de l'Assemblée, rallié au PDG. Dinguiraye est la cité fondée au XIXe siècle par El Hadj Omar Tall, foyer spirituel et historique majeur de la Guinée.", leurres: ["Keïta Ouremba", "Barry Baba Alimou", "Diallo Oumar"], tous: [{ nom: "Tall Mody Habidou", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Dubréka",     circonscription1957: "Dubréka",     nom: "Soumah Nabi Issa",           role: "Conseiller territorial de Dubréka", fiche: "Conseiller territorial de Dubréka en 1957, sur la côte près de Conakry.", indice: "Conseiller territorial de Dubréka, sur la côte.", leurres: ["Soumah Moustapha", "Camara M'Balia", "Touré Dondo"], tous: [{ nom: "Soumah Nabi Issa", source: "1957" }, { nom: "Dr Roger Najib Accar", source: "1957" }, { nom: "Mme Camara M'Balia (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Faranah",     circonscription1957: "Faranah",     nom: "Condé Ansoumane",            role: "Conseiller territorial de Faranah", fiche: "Conseiller territorial de Faranah en 1957, aux sources du fleuve Niger.", indice: "Conseiller territorial de Faranah, aux sources du Niger.", leurres: ["Keïta El Hadj Mory", "Barry Baba Alimou", "Mara Diomba"], tous: [{ nom: "Condé Ansoumane", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Forécariah",  circonscription1957: "Forécariah",  nom: "Touré Dondo",                role: "Conseiller territorial de Forécariah", fiche: "Conseiller territorial de Forécariah en 1957, au sud de la Basse-Côte.", indice: "Conseiller territorial de Forécariah, au sud de la côte.", leurres: ["Soumah Nabi Issa", "Touré Sékou", "Camara Sankoumba"], tous: [{ nom: "Touré Dondo", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Gaoual",      circonscription1957: "Gaoual",      nom: "Diallo Aguibou",             role: "Conseiller territorial de Gaoual", fiche: "Conseiller territorial de Gaoual en 1957, dans le nord du Fouta.", indice: "Conseiller territorial de Gaoual.", leurres: ["Bounka Mané", "Diallo Ibrahima", "Sy Boubacar"], tous: [{ nom: "Bounka Mané", source: "1957" }, { nom: "Diallo Aguibou", source: "1957" }, { nom: "Condé (facteur PTT)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Guékédou",    circonscription1957: "Guéckédou",   nom: "Sangaré Toumani",            role: "Conseiller territorial de Guéckédou", fiche: "Conseiller territorial de Guéckédou en 1957, en Guinée forestière.", indice: "Conseiller territorial de Guéckédou, en forêt.", leurres: ["Joachim Eugène", "Traoré Tambakala", "Keïta Yéro"], tous: [{ nom: "Joachim Eugène", source: "1957" }, { nom: "Sangaré Toumani", source: "1957" }, { nom: "Traoré Tambakala", source: "1957" }, { nom: "Keïta Yéro (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Kankan",      circonscription1957: "Kankan",      nom: "Diané Lansana",              role: "Conseiller territorial de Kankan", fiche: "Conseiller territorial de Kankan en 1957, grande cité de la Haute-Guinée sur le Milo.", indice: "Conseiller territorial de Kankan, capitale de la Haute-Guinée.", leurres: ["Kaba Lamine Ibrahima", "Cheick Fanta Mamadi", "Camara Raphaël"], tous: [{ nom: "Diané Lansana", source: "1957" }, { nom: "Kaba Lamine Ibrahima", source: "1957" }, { nom: "Cheick Fanta Mamadi (posthume)", source: "croix1959" }, { nom: "Camara Raphaël (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Kindia",      circonscription1957: "Kindia",      nom: "Sylla Seny Faciné",          role: "Conseiller territorial de Kindia", fiche: "Conseiller territorial de Kindia en 1957, la cité des agrumes en Basse-Guinée.", indice: "Conseiller territorial de Kindia, la cité des agrumes.", leurres: ["Sylla Mamadi Fodé", "Touré Dondo", "Soumah Nabi Issa"], tous: [{ nom: "Sylla Seny Faciné", source: "1957" }, { nom: "Jean-Eugène Mignard", source: "1957" }, { nom: "Sylla Mamadi Fodé (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Kissidougou", circonscription1957: "Kissidougou", nom: "Keïta El Hadj Mory",         role: "Conseiller territorial de Kissidougou", fiche: "Conseiller territorial de Kissidougou en 1957, à la lisière de la forêt.", indice: "Conseiller territorial de Kissidougou, à la lisière de la forêt.", leurres: ["Mara Diomba", "Bakary Fina", "Condé Ansoumane"], tous: [{ nom: "Keïta El Hadj Mory", source: "1957" }, { nom: "Mara Diomba", source: "1957" }, { nom: "Bakary Fina (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Kouroussa",   circonscription1957: "Kouroussa",   nom: "Keïta Ouremba",              role: "Questeur de l'Assemblée nationale", fiche: "Questeur de l'Assemblée nationale constituante, élu de Kouroussa sur le fleuve Niger.", indice: "Questeur de l'Assemblée, élu de Kouroussa sur le Niger.", leurres: ["Camara Moussa Sanguiana", "Diané Lansana", "Cissé Karamoko"], tous: [{ nom: "Camara Moussa Sanguiana", source: "1957" }, { nom: "Keïta Ouremba", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Labé",        circonscription1957: "Labé",        nom: "Diallo Saïfoulaye",          role: "Président de l'Assemblée nationale", fiche: "Président de l'Assemblée nationale constituante, élu de Labé : l'une des plus grandes figures du Fouta et second du PDG.", indice: "Président de l'Assemblée nationale, grande figure du Fouta, élu de Labé.", leurres: ["Baldé Mamadou Tanou", "Diakité M'Bemba", "Diallo Alpha Mamadou"], tous: [{ nom: "Diallo Saïfoulaye", source: "1957" }, { nom: "Baldé Mamadou Tanou", source: "1957" }, { nom: "Demarchelier Jacques", source: "1957" }, { nom: "Diakité M'Bemba", source: "1957" }, { nom: "Diallo Alpha Mamadou", source: "1957" }, { nom: "Diallo Amadou Telivel", source: "1957" }, { nom: "Diallo Bakary (posthume)", source: "croix1959" }, { nom: "Chérif de Sangalé (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Macenta",     circonscription1957: "Macenta",     nom: "Louis Lansana Béavogui",     role: "Élu de Macenta · futur premier Premier ministre de Guinée", fiche: "Élu de Macenta en 1957, en Guinée forestière. Médecin de formation, il deviendra en 1972 le premier Premier ministre de la République de Guinée.", indice: "Élu de Macenta, il deviendra le premier Premier ministre de Guinée.", leurres: ["Camara Mory", "Guèye Doudou", "Soumaoro Séoro"], tous: [{ nom: "Béavogui Koman", source: "1957" }, { nom: "Camara Mory", source: "1957" }, { nom: "Guèye Doudou", source: "1957" }, { nom: "Camara Kaman (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Mali",        circonscription1957: "Mali",        nom: "Diallo Oumar",               role: "Conseiller territorial de Mali", fiche: "Conseiller territorial de Mali en 1957, le point le plus élevé du Fouta-Djalon.", indice: "Conseiller territorial de Mali, le toit du Fouta-Djalon.", leurres: ["Sow Souleymane", "Barry Mamadou Diouldé", "Diallo Aguibou"], tous: [{ nom: "Diallo Oumar", source: "1957" }, { nom: "Sow Souleymane", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Mamou",       circonscription1957: "Mamou",       nom: "Barry Alpha Oumar",          role: "Conseiller territorial de Mamou", fiche: "Conseiller territorial de Mamou en 1957, carrefour entre la Basse-Guinée, le Fouta et la Haute-Guinée.", indice: "Conseiller territorial de Mamou, carrefour du pays.", leurres: ["Doumbouya Bela", "Diallo Thiemo Djibi", "Bah Thierno Ibrahima"], tous: [{ nom: "Barry Alpha Oumar", source: "1957" }, { nom: "Doumbouya Bela", source: "1957" }, { nom: "Diallo Thiemo Djibi (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Nzérékoré",   circonscription1957: "N'Zérékoré",  nom: "Tounkara Jean Faragué",      role: "Secrétaire de l'Assemblée nationale", fiche: "Secrétaire de l'Assemblée nationale constituante, élu de N'Zérékoré, grande ville de la Guinée forestière.", indice: "Secrétaire de l'Assemblée, élu de N'Zérékoré, capitale de la forêt.", leurres: ["Doré Lama", "Gnan Félix Matos", "Soumaoro Séoro"], tous: [{ nom: "Doré Lama", source: "1957" }, { nom: "Gnan Félix Matos", source: "1957" }, { nom: "Tounkara Jean Faragué", source: "1957" }, { nom: "Soumaoro Séoro (posthume)", source: "croix1959" }, { nom: "N'Faly Touré (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Pita",        circonscription1957: "Pita",        nom: "Ibrahima Barry dit Barry III",role: "Chef du MSA/PRA · élu de Pita", indice: "Élu de Pita et chef d'un grand parti (MSA/PRA) : l'un des trois leaders de 1958.", fiche: "Élu de Pita, dirigeant du Mouvement Socialiste Africain puis du PRA-Guinée. Avec Barry Diawadou et Sékou Touré, il fait converger les partis vers le NON au référendum de 1958, scellant l'unité pour l'indépendance.", chefDeParti: "MSA / PRA-Guinée", leurres: ["Bah Thierno Ousmane", "Thiam Mamadou", "Barry Diawadou"], tous: [{ nom: "Bah Thierno Ousmane", source: "1957" }, { nom: "Thiam Mamadou", source: "1957" }, { nom: "Ibrahima Barry dit Barry III", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Siguiri",     circonscription1957: "Siguiri",     nom: "Cissé Karamoko",             role: "Conseiller territorial de Siguiri", fiche: "Conseiller territorial de Siguiri en 1957, pays de l'or sur le haut Niger.", indice: "Conseiller territorial de Siguiri, le pays de l'or.", leurres: ["Doumbouya Kouramoudou", "Traoré Falaye", "Konso Magassouba"], tous: [{ nom: "Cissé Karamoko", source: "1957" }, { nom: "Doumbouya Kouramoudou", source: "1957" }, { nom: "Traoré Falaye (posthume)", source: "croix1959" }, { nom: "Cissé Karamoko (posthume)", source: "croix1959" }, { nom: "Konso Magassouba (posthume)", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Télimélé",    circonscription1957: "Télimélé",    nom: "Diallo Ibrahima",            role: "Conseiller territorial de Télimélé", fiche: "Conseiller territorial de Télimélé en 1957, dans l'ouest du Fouta.", indice: "Conseiller territorial de Télimélé.", leurres: ["Sy Boubacar", "Diallo Aguibou", "Thiam Amadou"], tous: [{ nom: "Diallo Ibrahima", source: "1957" }, { nom: "Sy Boubacar", source: "1957" }, { nom: "Thiam Amadou", source: "croix1959" }, { nom: "Fofana Karamadi", source: "croix1959" }, { nom: "Diallo Diouhé", source: "croix1959" }], source: "1957", valide: true },
    { prefecture: "Tougué",      circonscription1957: "Tougué",      nom: "Barry Mamadou Diouldé",      role: "Conseiller territorial de Tougué", fiche: "Conseiller territorial de Tougué en 1957, dans le Fouta-Djalon.", indice: "Conseiller territorial de Tougué, dans le Fouta.", leurres: ["Diallo Oumar", "Sow Souleymane", "Bah Thierno Ibrahima"], tous: [{ nom: "Barry Mamadou Diouldé", source: "1957" }], source: "1957", valide: true },
    { prefecture: "Koundara",    circonscription1957: "Youkounkoun",  nom: "Keïta Kéméko",               role: "Conseiller territorial de Youkounkoun (Koundara)", fiche: "Élu de Youkounkoun (l'actuelle Koundara) en 1957, à l'extrême nord-ouest, frontière du Sénégal et de la Guinée-Bissau.", indice: "Conseiller territorial de Youkounkoun, l'actuelle Koundara, à la frontière.", leurres: ["Kourouma Mamadi", "Pata Gobaye", "Diallo Aguibou"], tous: [{ nom: "Keïta Kéméko", source: "1957" }, { nom: "Keïta Kémoko (député)", source: "croix1959" }, { nom: "Kourouma Mamadi (Saraboïdo)", source: "croix1959" }, { nom: "Pata Gobaye", source: "croix1959" }], source: "1957", valide: true },

    { prefecture: "Coyah", circonscription1957: "Créée après 1957 — rattachée à Dubréka", nom: "Soumah Nabi Issa", role: "Conseiller territorial de Dubréka", indice: "Coyah, créée après 1957 : on y honore la figure de sa circonscription d'origine, Dubréka.", fiche: "Conseiller territorial de Dubréka en 1957, sur la côte près de Conakry.", rattachement: "Dubréka", mention: "Coyah a été créée après 1957. La figure présentée est rattachée à sa circonscription d'origine : Dubréka.", leurres: [], source: "rattachement", valide: true },
    { prefecture: "Fria", circonscription1957: "Créée après 1957 — rattachée à Boké", nom: "Camara Sankoumba", role: "Conseiller territorial de Boké", indice: "Fria, créée après 1957 : on y honore la figure de sa circonscription d'origine, Boké.", fiche: "Conseiller territorial de Boké en 1957, la porte de la Basse-Côte au bord du Rio Nunez, ancienne place forte de l'histoire de la Guinée.", rattachement: "Boké", mention: "Fria a été créée après 1957. La figure présentée est rattachée à sa circonscription d'origine : Boké.", leurres: [], source: "rattachement", valide: true },
    { prefecture: "Kérouané", circonscription1957: "Créée après 1957 — rattachée à Kankan", nom: "Diané Lansana", role: "Conseiller territorial de Kankan", indice: "Kérouané, créée après 1957 : on y honore la figure de sa circonscription d'origine, Kankan.", fiche: "Conseiller territorial de Kankan en 1957, grande cité de la Haute-Guinée sur le Milo.", rattachement: "Kankan", mention: "Kérouané a été créée après 1957. La figure présentée est rattachée à sa circonscription d'origine : Kankan.", leurres: [], source: "rattachement", valide: true },
    { prefecture: "Koubia", circonscription1957: "Créée après 1957 — rattachée à Tougué", nom: "Barry Mamadou Diouldé", role: "Conseiller territorial de Tougué", indice: "Koubia, créée après 1957 : on y honore la figure de sa circonscription d'origine, Tougué.", fiche: "Conseiller territorial de Tougué en 1957, dans le Fouta-Djalon.", rattachement: "Tougué", mention: "Koubia a été créée après 1957. La figure présentée est rattachée à sa circonscription d'origine : Tougué.", leurres: [], source: "rattachement", valide: true },
    { prefecture: "Lélouma", circonscription1957: "Créée après 1957 — rattachée à Labé", nom: "Diallo Saïfoulaye", role: "Président de l'Assemblée nationale", indice: "Lélouma, créée après 1957 : on y honore la figure de sa circonscription d'origine, Labé.", fiche: "Président de l'Assemblée nationale constituante, élu de Labé : l'une des plus grandes figures du Fouta et second du PDG.", rattachement: "Labé", mention: "Lélouma a été créée après 1957. La figure présentée est rattachée à sa circonscription d'origine : Labé.", leurres: [], source: "rattachement", valide: true },
    { prefecture: "Lola", circonscription1957: "Créée après 1957 — rattachée à Nzérékoré", nom: "Tounkara Jean Faragué", role: "Secrétaire de l'Assemblée nationale", indice: "Lola, créée après 1957 : on y honore la figure de sa circonscription d'origine, Nzérékoré.", fiche: "Secrétaire de l'Assemblée nationale constituante, élu de N'Zérékoré, grande ville de la Guinée forestière.", rattachement: "Nzérékoré", mention: "Lola a été créée après 1957. La figure présentée est rattachée à sa circonscription d'origine : Nzérékoré.", leurres: [], source: "rattachement", valide: true },
    { prefecture: "Mandiana", circonscription1957: "Créée après 1957 — rattachée à Kankan", nom: "Diané Lansana", role: "Conseiller territorial de Kankan", indice: "Mandiana, créée après 1957 : on y honore la figure de sa circonscription d'origine, Kankan.", fiche: "Conseiller territorial de Kankan en 1957, grande cité de la Haute-Guinée sur le Milo.", rattachement: "Kankan", mention: "Mandiana a été créée après 1957. La figure présentée est rattachée à sa circonscription d'origine : Kankan.", leurres: [], source: "rattachement", valide: true },
    { prefecture: "Yomou", circonscription1957: "Créée après 1957 — rattachée à Macenta", nom: "Camara Mory", role: "Élu de Macenta 1957 · Compagnon de l'Indépendance", indice: "Yomou, créée après 1957 : on y honore un autre député de sa circonscription d'origine, Macenta.", fiche: "Camara Mory fut élu député de Macenta en 1957, aux côtés de Louis Lansana Béavogui et de Guèye Doudou. Compagnon de l'Indépendance de la première heure, il représente la Guinée forestière au sein de l'Assemblée territoriale.", rattachement: "Macenta", mention: "Yomou a été créée après 1957. Camara Mory, autre député de Macenta 1957, y est honoré (Béavogui figure déjà à Macenta).", leurres: [], source: "rattachement", valide: true },

    /* --- Circonscriptions sans siège en 1957 → complétées par la Croix 1959-60 (À VALIDER) --- */
    { prefecture: "Boffa",       circonscription1957: "Boffa (rattachée à la Basse-Guinée en 1957)", nom: "Soumah Moussa", role: "Croix du Compagnon — Tougnifili (Boffa)", fiche: "Honoré de la Croix du Compagnon de l'Indépendance, originaire de Tougnifili, dans la préfecture de Boffa, sur la côte.", indice: "Honoré de la Croix du Compagnon, originaire de Tougnifili, à Boffa.", leurres: ["El-hadj Camara Boubacar", "Touré Dondo", "Soumah Nabi Issa"], tous: [{ nom: "Soumah Moussa (Tougnifili)", source: "croix1959" }, { nom: "El-hadj Camara Boubacar (Khouréralandé)", source: "croix1959" }], source: "croix1959", valide: false },
  ],

  /* --- MODE « FEMMES DE L'INDÉPENDANCE » (volet séparé) --- */
  /* Croix du Compagnon 1959-60. La plupart rattachées à Conakry/quartiers.
     Présentées comme galerie d'honneur ; certaines plaçables (Tondon→Dubréka). */
  femmes: [
    { nom: "Camara M'Balia",     lieu: "Tondon",            prefecture: "Dubréka",  role: "Croix du Compagnon à titre posthume — figure de la résistance", source: "croix1959", valide: false, emblematique: true },
    { nom: "Camara Loffo",       lieu: "Conakry",           prefecture: "Conakry",  role: "Sage-femme, Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Bangoura Mafori",    lieu: "Conakry",           prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Doumbouya Mama",     lieu: "Boulbinet (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Diallo Nènè",        lieu: "Conakry",           prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "N'Diaye Aïssatou",   lieu: "Boulbinet (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Keïta Fatou",        lieu: "Dixinn (Conakry)",  prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Cissé Aïssatou",     lieu: "Landréah (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Soumah Aïssata",     lieu: "Almamya (Conakry)", prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Kéita Filani Saran", lieu: "Madina (Conakry)",  prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Touré Mawa",         lieu: "Sandervalia (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Nabiya Haïdara",     lieu: "Almamya (Conakry)", prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Soumah Mabinti",     lieu: "Kolea (Conakry)",   prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Kaba N'Naba",        lieu: "Boussoura (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Kaba Kouloumba Ciré",lieu: "Coronthie (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Bangoura Sayon",     lieu: "Sandervalia (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Touré Mamadi",       lieu: "Téminétaye (Conakry)", prefecture: "Conakry", role: "Présidente de Téminétaye, Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Sylla Mayalan",      lieu: "Matam (Conakry)",   prefecture: "Conakry",  role: "Croix du Compagnon", source: "croix1959", valide: false },
    { nom: "Doumbouya N'Youla",  lieu: "Sandervalia (Conakry)", prefecture: "Conakry", role: "Croix du Compagnon", source: "croix1959", valide: false }
  ]
};
